// Public compatibility facade; one API registration keeps cache tags and generated hooks shared.
import { baseApi } from '@/shared/api/baseApi'
import { createCatalogEndpoints } from './autocare/catalog.endpoints'
import { createChatEndpoints } from './autocare/chat.endpoints'
import { createReviewsEndpoints } from './autocare/reviews.endpoints'
import { createProvidersEndpoints } from './autocare/providers.endpoints'
import { createRequestsEndpoints } from './autocare/requests.endpoints'
import { createGovernanceEndpoints } from './autocare/governance.endpoints'
import { createResourcesEndpoints } from './autocare/resources.endpoints'
import { createWorkspaceEndpoints } from './autocare/workspace.endpoints'
import { createBonusesEndpoints } from './autocare/bonuses.endpoints'
import { createMarketplaceEndpoints } from './autocare/marketplace.endpoints'

export type { AutoCareApiLocationZone, AutoCareApiMarket, AutoCareApiMarketCountry, AutoCareApiServiceDefinition, AutoCareCatalogGapRequest, AutoCareVehicleBrand, AutoCareVehicleEngine, AutoCareVehicleModel, CreateAutoCareCatalogGapRequestInput, CreateSuperAdminAutoCareMarketInput, CreateSuperAdminAutoCareMarketZoneInput, CreateSuperAdminMarketCountryInput, DecideAutoCareCatalogGapRequestInput, SuperAdminMarketHierarchy, SuperAdminMarketProfileInput, UpdateAdminAutoCareServiceDefinitionInput, UpdateSuperAdminAutoCareMarketHierarchyInput, UpdateSuperAdminAutoCareMarketInput, UpdateSuperAdminAutoCareMarketZoneInput, UpdateSuperAdminMarketCountryInput } from './autocare/catalog.types'
export type { AdminAutoCareModerationEvidence, AdminAutoCareProvider, AutoCareAppeal, AutoCarePriceBenchmark, AutoCareQualityMonitoring, AutoCareTrustEvidence, AutoCareTrustResponse, AutoCareTrustSnapshot, CreateAutoCareAppealInput, DeleteSuperAdminResourceResponse, SuperAdminPlatformOverview, SuperAdminTrustPolicy, UpdateSuperAdminTrustPolicyInput } from './autocare/governance.types'
export type { AutoCareApiDiscoveryItem, AutoCareApiDiscoveryResponse, AutoCareApiOffer, AutoCareApiProvider, AutoCareApiProviderProfile, AutoCareDiscoveryQuery, AutoCareFavorite, AutoCareProviderAnalytics, CreateOwnerAutoCareProviderInput, OwnerAutoCareEvidence, UpdateAutoCareCommunicationSettingsInput, UpdateAutoCareOfferInput, UploadOwnerAutoCareProviderMediaInput } from './autocare/providers.types'
export type { AutoCareBonusAccount, AutoCareBonusLedgerEntry, AutoCareBonusProgram, GrantAutoCareBonusInput, OwnerAutoCareBonusLiability, OwnerAutoCareBonusProgramInput, RedeemAutoCareBonusInput } from './autocare/bonuses.types'
export type { AcceptAutoCareProviderInvitationInput, AutoCareOwnerWorkspaceAccess, AutoCareProviderChangeRequest, AutoCareProviderInvitation, AutoCareProviderInvitationAcceptResponse, AutoCareProviderMember, AutoCareProviderMembersResponse, CreateAutoCareProviderChangeRequestInput, CreateAutoCareProviderInvitationInput, DecideAutoCareProviderChangeRequestInput } from './autocare/workspace.types'
export type { AdminAutoCareReview, AutoCareApiProviderReviews, AutoCareApiReview, AutoCareCommunityMetrics, AutoCareCommunityProfile, AutoCareReviewPromo, CreateAutoCareReviewInput, IssueAutoCareReviewPromoInput, OwnerAutoCareReviews, OwnerAutoCareReviewsProvider, PublicAutoCareCommunityProfile, RedeemAutoCareReviewPromoInput, UpdateAdminAutoCareReviewStatusInput, UpdateAutoCareReviewInput } from './autocare/reviews.types'
export { autoCareOfferSchema } from './autocare/providers.schemas'
export { autoCareQuoteSchema, autoCareServiceAttachmentSchema } from './autocare/requests.schemas'
export type { AutoCareAvailability, AutoCareBookingSnapshot, AutoCareQuoteDecisionInput, AutoCareQuoteLineItem, AutoCareRepairEvent, AutoCareReschedule, AutoCareServiceAttachment, AutoCareServiceConversation, AutoCareServiceMessage, AutoCareServiceMessageOffer, AutoCareServiceQuote, AutoCareServiceRequest, CompleteAutoCareServiceRequestInput, CreateAutoCareServiceAttachmentInput, CreateAutoCareServiceMessageInput, CreateAutoCareServiceOfferInput, CreateAutoCareServiceQuoteInput, CreateAutoCareServiceRequestInput, DecideAutoCareServiceOfferInput, GetAutoCareAttachmentObjectUrlInput, GetAutoCareServiceConversationInput } from './autocare/requests.types'
export type { AdminAutoCareChatReportQuery, AssignAutoCareChatReportInput, AutoCareChatBlock, AutoCareChatConversation, AutoCareChatReport, AutoCareChatReportListQuery, AutoCareChatReportPage, AutoCareChatRestriction, AutoCareChatThread, AutoCareChatThreadType, CreateAutoCareChatAttachmentInput, CreateAutoCareChatBlockInput, CreateAutoCareChatInput, CreateAutoCareChatMessageInput, CreateAutoCareChatReportInput, DecideAutoCareChatReportInput, DeleteAutoCareChatMessageResponse, ExtendAutoCareChatReportAccessInput, RevokeAutoCareChatBlockInput } from './autocare/chat.types'
export type { AutoCareBroadcastOffer, AutoCareBroadcastRequest, AutoCareExpertQuestion, AutoCareFleet, AutoCareFleetVehicle, AutoCareGuaranteeClaim, CreateAutoCareBroadcastOfferInput, CreateAutoCareBroadcastRequestInput, CreateAutoCareExpertQuestionInput, CreateAutoCareFleetInput, CreateAutoCareFleetVehicleInput, CreateAutoCareGuaranteeClaimInput } from './autocare/marketplace.types'
export type { AutoCareCapacityReservation, AutoCareCapacityResource, CreateAutoCareCapacityResourceInput, UpdateAutoCareCapacityResourceInput } from './autocare/resources.types'

export const autoCareApi = baseApi.injectEndpoints({
    endpoints: (build) => ({
        ...createCatalogEndpoints(build),
        ...createChatEndpoints(build),
        ...createReviewsEndpoints(build),
        ...createProvidersEndpoints(build),
        ...createRequestsEndpoints(build),
        ...createGovernanceEndpoints(build),
        ...createResourcesEndpoints(build),
        ...createWorkspaceEndpoints(build),
        ...createBonusesEndpoints(build),
        ...createMarketplaceEndpoints(build),
    }),
})

export const {
    useGetAutoCareDiscoveryQuery,
    useLazyGetAutoCareDiscoveryQuery,
    useGetAutoCareMarketsQuery,
    useUpdateSuperAdminAutoCareMarketMutation,
    useGetSuperAdminMarketHierarchyQuery,
    useCreateSuperAdminMarketCountryMutation,
    useUpdateSuperAdminMarketCountryMutation,
    useDeleteSuperAdminMarketCountryMutation,
    useCreateSuperAdminAutoCareMarketMutation,
    useUpdateSuperAdminAutoCareMarketHierarchyMutation,
    useDeleteSuperAdminAutoCareMarketMutation,
    useCreateSuperAdminAutoCareMarketZoneMutation,
    useUpdateSuperAdminAutoCareMarketZoneMutation,
    useDeleteSuperAdminAutoCareMarketZoneMutation,
    useGetAutoCareLocationZonesQuery,
    useGetOwnerAutoCareProvidersQuery,
    useGetOwnerAutoCareCapacityResourcesQuery,
    useGetOwnerAutoCareCapacityReservationsQuery,
    useCreateOwnerAutoCareCapacityResourceMutation,
    useUpdateOwnerAutoCareCapacityResourceMutation,
    useUpdateOwnerAutoCareCommunicationSettingsMutation,
    useGetOwnerAutoCareWorkspaceAccessQuery,
    useGetOwnerAutoCareProviderAnalyticsQuery,
    useGetOwnerAutoCareProviderEvidenceQuery,
    useGetOwnerAutoCareBonusLiabilityQuery,
    useGetOwnerAutoCareProviderMembersQuery,
    useInviteAutoCareProviderMemberMutation,
    useRevokeAutoCareProviderInvitationMutation,
    useAcceptAutoCareProviderInvitationMutation,
    useGetOwnerAutoCareProviderChangeRequestsQuery,
    useCreateOwnerAutoCareProviderChangeRequestMutation,
    useCancelOwnerAutoCareProviderChangeRequestMutation,
    useGetAdminAutoCareProviderChangeRequestsQuery,
    useDecideAdminAutoCareProviderChangeRequestMutation,
    useCreateAutoCareCatalogGapRequestMutation,
    useGetAdminCatalogGapRequestsQuery,
    useDecideAdminCatalogGapRequestMutation,
    useGetAdminAutoCareChatReportsQuery,
    useLazyGetAdminAutoCareChatReportsQuery,
    useDecideAdminAutoCareChatReportMutation,
    useAssignAdminAutoCareChatReportMutation,
    useExtendAdminAutoCareChatReportAccessMutation,
    useGetMyAutoCareBonusAccountsQuery,
    useGetOwnerAutoCareBonusProgramQuery,
    useUpsertOwnerAutoCareBonusProgramMutation,
    useUpdateOwnerAutoCareOfferMutation,
    useGetOwnerAutoCareProviderReviewsQuery,
    useGetOwnerAutoCareReviewsQuery,
    useIssueOwnerAutoCareReviewPromoMutation,
    useGetMyAutoCareReviewsQuery,
    useGetMyAutoCareAppealsQuery,
    useCreateAutoCareAppealMutation,
    useWithdrawAutoCareAppealMutation,
    useCreateAutoCareReviewMutation,
    useRedeemAutoCareReviewPromoMutation,
    useUpdateAutoCareReviewMutation,
    useGetAdminAutoCareProvidersQuery,
    useUpdateAdminAutoCareProviderStatusMutation,
    useGetAdminAutoCareQualityMonitoringQuery,
    useGetAdminAutoCareAppealsQuery,
    useDecideAdminAutoCareAppealMutation,
    useGetAdminAutoCareModerationEvidenceQuery,
    useDecideAdminAutoCareModerationEvidenceMutation,
    useGetSuperAdminPlatformOverviewQuery,
    useGetSuperAdminTrustPolicyQuery,
    useUpdateSuperAdminTrustPolicyMutation,
    useUploadOwnerAutoCareProviderLogoMutation,
    useUploadOwnerAutoCareProviderMediaMutation,
    useGetAutoCareProviderProfileQuery,
    useGetAutoCareProviderReviewsQuery,
    useGetMyAutoCareCommunityProfileQuery,
    useUpdateMyAutoCareCommunityProfileMutation,
    useGetPublicAutoCareCommunityProfileQuery,
    useGetMyAutoCareHelpfulReviewIdsQuery,
    useVoteAutoCareReviewHelpfulMutation,
    useGetAutoCareFavoritesQuery,
    useAddAutoCareFavoriteMutation,
    useRemoveAutoCareFavoriteMutation,
    useSyncAutoCareFavoritesMutation,
    useGetAutoCareAvailabilityQuery,
    useGetAutoCareFairPriceQuery,
    useGetAutoCareProviderTrustQuery,
    useGetAutoCareServiceDefinitionsQuery,
    useUpdateAdminAutoCareServiceDefinitionMutation,
    useGetVehicleCatalogQuery,
    useGetFeaturedAutoCareReviewsQuery,
    useGetAdminAutoCareReviewsQuery,
    useUpdateAdminAutoCareReviewStatusMutation,
    useCreateOwnerAutoCareProviderMutation,
    useCreateAutoCareServiceRequestMutation,
    useGetMyAutoCareServiceRequestsQuery,
    useGetAutoCareChatsQuery,
    useGetAutoCareRequestChatThreadQuery,
    useCreateAutoCareChatMutation,
    useGetAutoCareChatQuery,
    useCreateAutoCareChatMessageMutation,
    useCreateAutoCareChatReportMutation,
    useGetMyAutoCareChatReportsQuery,
    useLazyGetMyAutoCareChatReportsQuery,
    useDeleteAutoCareChatMessageMutation,
    useCreateAutoCareChatBlockMutation,
    useRevokeAutoCareChatBlockMutation,
    useMarkAutoCareChatReadMutation,
    useCreateAutoCareChatAttachmentMutation,
    useGetAutoCareServiceRequestQuery,
    useGetAutoCareRepairTimelineQuery,
    useCreateAutoCareBroadcastRequestMutation,
    useGetMyAutoCareBroadcastRequestsQuery,
    useGetAutoCareBroadcastRequestQuery,
    useGetOwnerAutoCareBroadcastRequestsQuery,
    useCreateAutoCareBroadcastOfferMutation,
    useCreateAutoCareGuaranteeClaimMutation,
    useGetMyAutoCareGuaranteeClaimsQuery,
    useCreateAutoCareExpertQuestionMutation,
    useGetMyAutoCareExpertQuestionsQuery,
    useGetMyAutoCareFleetsQuery,
    useCreateAutoCareFleetMutation,
    useCreateAutoCareFleetVehicleMutation,
    useGetAutoCareServiceConversationQuery,
    useCreateAutoCareServiceMessageMutation,
    useCreateAutoCareServiceOfferMutation,
    useDecideAutoCareServiceOfferMutation,
    useMarkAutoCareServiceConversationReadMutation,
    useCreateAutoCareServiceAttachmentMutation,
    useGetAutoCareAttachmentObjectUrlQuery,
    useConfirmAutoCareServiceRequestMutation,
    useCancelAutoCareServiceRequestMutation,
    useDecideAutoCareServiceRescheduleMutation,
    useAcceptAutoCareServiceQuoteMutation,
    useDeclineAutoCareServiceQuoteMutation,
    useGetOwnerAutoCareServiceRequestsQuery,
    useRevokeAutoCareProviderMembershipMutation,
    useRedeemAutoCareBonusMutation,
    useGrantAutoCareBonusMutation,
    useConfirmOwnerAutoCareServiceRequestMutation,
    useCreateAutoCareServiceQuoteMutation,
    useRequestAutoCareServiceRescheduleMutation,
    useMarkAutoCareServiceRequestNoShowMutation,
    useCompleteAutoCareServiceRequestMutation,
} = autoCareApi
