import { enTranslations } from './en'

type AutoCareLocale = 'ru' | 'ro' | 'es' | 'de' | 'fr' | 'pt' | 'zh' | 'ja' | 'ko' | 'ar' | 'tr' | 'hi'

const autocareOverrides = {
    ru: { heroTitle: 'Найдите лучший автосервис рядом', heroDescription: 'Сравните цены, рейтинги и время записи за пару кликов', byService: 'По услуге', byProvider: 'По автосервису', searchAction: 'Найти сервисы', resultsTitle: 'Сравните автосервисы', bookAction: 'Выбрать и записаться', detailsAction: 'Подробнее', chatSend: 'Отправить', radiusOption: '{{value}} км', providerMobileService: 'Выездной сервис', providerMobileServiceWithRadius: 'Выездной сервис · до {{radius}} км', providerPickupDelivery: 'Заберём и доставим авто', heroMapLabel: 'Карта поиска автосервисов', heroMapZoomLevel: 'Масштаб карты: {{percent}} процентов', locationServiceOne: 'автосервис', locationServicePlural: 'автосервисов' },
    ro: { heroTitle: 'Găsește cel mai bun service auto în apropiere', heroDescription: 'Compară prețuri, evaluări și programări în câteva clicuri', byService: 'După serviciu', byProvider: 'După service', searchAction: 'Găsește service-uri', resultsTitle: 'Compară service-uri auto', resultCount: '{{count}} service-uri găsite', bookAction: 'Alege și rezervă', detailsAction: 'Detalii', chatSend: 'Trimite', radiusOption: '{{value}} km', providerMobileService: 'Service mobil', providerMobileServiceWithRadius: 'Service mobil · până la {{radius}} km', providerPickupDelivery: 'Ridicare și livrare auto', heroMapLabel: 'Hartă pentru găsirea service-urilor auto', heroMapZoomLevel: 'Zoom hartă: {{percent}} la sută', locationServiceOne: 'service', locationServicePlural: 'service-uri' },
    es: { heroTitle: 'Encuentra el mejor taller cerca de ti', heroDescription: 'Compara precios, valoraciones y citas en unos pocos clics', byService: 'Por servicio', byProvider: 'Por taller', searchAction: 'Buscar talleres', resultsTitle: 'Compara servicios de auto', resultCount: '{{count}} talleres encontrados', bookAction: 'Elegir y reservar', detailsAction: 'Detalles', chatSend: 'Enviar', radiusOption: '{{value}} km', providerMobileService: 'Servicio móvil', providerMobileServiceWithRadius: 'Servicio móvil · hasta {{radius}} km', providerPickupDelivery: 'Recogida y entrega del vehículo', heroMapLabel: 'Mapa de búsqueda de talleres', heroMapZoomLevel: 'Zoom del mapa: {{percent}} por ciento', locationServiceOne: 'taller', locationServicePlural: 'talleres' },
    de: { heroTitle: 'Finde die beste Werkstatt in deiner Nähe', heroDescription: 'Vergleiche Preise, Bewertungen und Termine mit wenigen Klicks', byService: 'Nach Leistung', byProvider: 'Nach Werkstatt', searchAction: 'Werkstätten finden', resultsTitle: 'Autodienste vergleichen', bookAction: 'Auswählen und buchen', detailsAction: 'Details', chatSend: 'Senden', radiusOption: '{{value}} km', providerMobileService: 'Mobiler Service', providerMobileServiceWithRadius: 'Mobiler Service · bis {{radius}} km', providerPickupDelivery: 'Abholung und Lieferung des Fahrzeugs', heroMapLabel: 'Karte zur Suche nach Autowerkstätten', heroMapZoomLevel: 'Kartenzoom: {{percent}} Prozent', locationServiceOne: 'Werkstatt', locationServicePlural: 'Werkstätten' },
    fr: { heroTitle: 'Trouvez le meilleur garage près de chez vous', heroDescription: 'Comparez les prix, avis et créneaux en quelques clics', byService: 'Par service', byProvider: 'Par garage', searchAction: 'Trouver des garages', resultsTitle: 'Comparez les services auto', bookAction: 'Choisir et réserver', detailsAction: 'Détails', chatSend: 'Envoyer', radiusOption: '{{value}} km', providerMobileService: 'Service mobile', providerMobileServiceWithRadius: 'Service mobile · jusqu’à {{radius}} km', providerPickupDelivery: 'Prise en charge et livraison du véhicule', heroMapLabel: 'Carte de recherche de garages', heroMapZoomLevel: 'Zoom de la carte : {{percent}} pour cent', locationServiceOne: 'garage', locationServicePlural: 'garages' },
    pt: { heroTitle: 'Encontre a melhor oficina perto de você', heroDescription: 'Compare preços, avaliações e horários em poucos cliques', byService: 'Por serviço', byProvider: 'Por oficina', searchAction: 'Encontrar oficinas', resultsTitle: 'Compare serviços automotivos', bookAction: 'Escolher e agendar', detailsAction: 'Detalhes', chatSend: 'Enviar', radiusOption: '{{value}} km', providerMobileService: 'Serviço móvel', providerMobileServiceWithRadius: 'Serviço móvel · até {{radius}} km', providerPickupDelivery: 'Recolha e entrega do veículo', heroMapLabel: 'Mapa de busca de oficinas', heroMapZoomLevel: 'Zoom do mapa: {{percent}} por cento', locationServiceOne: 'oficina', locationServicePlural: 'oficinas' },
    zh: { heroTitle: '查找附近最好的汽车服务', heroDescription: '只需几次点击即可比较价格、评价和预约时间', byService: '按服务', byProvider: '按服务商', searchAction: '查找服务商', resultsTitle: '比较汽车服务', bookAction: '选择并预约', detailsAction: '详情', chatSend: '发送', radiusOption: '{{value}} 公里', providerMobileService: '移动服务', providerMobileServiceWithRadius: '移动服务 · 最多 {{radius}} 公里', providerPickupDelivery: '车辆取送', heroMapLabel: '汽车服务搜索地图', heroMapZoomLevel: '地图缩放：{{percent}}%', locationServiceOne: '家汽车服务商', locationServicePlural: '家汽车服务商' },
    ja: { heroTitle: '近くの最適な自動車サービスを探す', heroDescription: '料金、レビュー、予約可能時間を数クリックで比較', byService: 'サービスから', byProvider: '店舗から', searchAction: 'サービスを探す', resultsTitle: '自動車サービスを比較', bookAction: '選択して予約', detailsAction: '詳細', chatSend: '送信', radiusOption: '{{value}} km', providerMobileService: '出張サービス', providerMobileServiceWithRadius: '出張サービス · 最大{{radius}} km', providerPickupDelivery: '車両の引き取りと納車', heroMapLabel: '自動車サービス検索マップ', heroMapZoomLevel: '地図のズーム：{{percent}}%', locationServiceOne: 'サービス', locationServicePlural: 'サービス' },
    ko: { heroTitle: '가까운 최고의 자동차 서비스를 찾아보세요', heroDescription: '몇 번의 클릭으로 가격, 후기, 예약 시간을 비교하세요', byService: '서비스별', byProvider: '정비소별', searchAction: '서비스 찾기', resultsTitle: '자동차 서비스 비교', bookAction: '선택하고 예약', detailsAction: '자세히 보기', chatSend: '보내기', radiusOption: '{{value}}km', providerMobileService: '출장 서비스', providerMobileServiceWithRadius: '출장 서비스 · 최대 {{radius}}km', providerPickupDelivery: '차량 픽업 및 배달', heroMapLabel: '자동차 서비스 검색 지도', heroMapZoomLevel: '지도 확대/축소: {{percent}}%', locationServiceOne: '서비스', locationServicePlural: '서비스' },
    ar: { heroTitle: 'اعثر على أفضل خدمة سيارات بالقرب منك', heroDescription: 'قارن الأسعار والتقييمات ومواعيد الحجز ببضع نقرات', byService: 'حسب الخدمة', byProvider: 'حسب مركز الخدمة', searchAction: 'ابحث عن خدمات', resultsTitle: 'قارن خدمات السيارات', bookAction: 'اختر واحجز', detailsAction: 'التفاصيل', chatSend: 'إرسال', radiusOption: '{{value}} كم', providerMobileService: 'خدمة متنقلة', providerMobileServiceWithRadius: 'خدمة متنقلة · حتى {{radius}} كم', providerPickupDelivery: 'استلام وتسليم السيارة', heroMapLabel: 'خريطة البحث عن خدمات السيارات', heroMapZoomLevel: 'تكبير الخريطة: {{percent}}٪', locationServiceOne: 'مركز خدمة', locationServicePlural: 'مراكز خدمة' },
    tr: { heroTitle: 'Yakınınızdaki en iyi oto servisini bulun', heroDescription: 'Fiyatları, yorumları ve randevu saatlerini birkaç tıklamayla karşılaştırın', byService: 'Hizmete göre', byProvider: 'Servise göre', searchAction: 'Servisleri bul', resultsTitle: 'Oto servislerini karşılaştırın', bookAction: 'Seç ve randevu al', detailsAction: 'Detaylar', chatSend: 'Gönder', radiusOption: '{{value}} km', providerMobileService: 'Mobil servis', providerMobileServiceWithRadius: 'Mobil servis · {{radius}} km’ye kadar', providerPickupDelivery: 'Aracı alma ve teslim etme', heroMapLabel: 'Oto servis arama haritası', heroMapZoomLevel: 'Harita yakınlaştırma: yüzde {{percent}}', locationServiceOne: 'servis', locationServicePlural: 'servis' },
    hi: { heroTitle: 'अपने पास की सर्वश्रेष्ठ ऑटो सेवा खोजें', heroDescription: 'कुछ क्लिक में कीमतों, रेटिंग और उपलब्ध समय की तुलना करें', byService: 'सेवा के अनुसार', byProvider: 'सर्विस सेंटर के अनुसार', searchAction: 'सेवाएं खोजें', resultsTitle: 'ऑटो सेवाओं की तुलना करें', bookAction: 'चुनें और बुक करें', detailsAction: 'विवरण', chatSend: 'भेजें', radiusOption: '{{value}} किमी', providerMobileService: 'मोबाइल सेवा', providerMobileServiceWithRadius: 'मोबाइल सेवा · {{radius}} किमी तक', providerPickupDelivery: 'वाहन पिकअप और डिलीवरी', heroMapLabel: 'ऑटो सेवा खोज मानचित्र', heroMapZoomLevel: 'मानचित्र ज़ूम: {{percent}} प्रतिशत', locationServiceOne: 'सर्विस सेंटर', locationServicePlural: 'सर्विस सेंटर' },
} as const satisfies Record<AutoCareLocale, Partial<typeof enTranslations.autocare>>

export function withAutoCareTranslations<T extends typeof enTranslations>(locale: AutoCareLocale, translations: T): T {
    return {
        ...translations,
        autocare: { ...translations.autocare, ...autocareOverrides[locale] },
    }
}
