import { enTranslations } from './en'

export type PopularLocale = 'es' | 'de' | 'fr' | 'pt' | 'zh' | 'ja' | 'ko' | 'ar' | 'tr' | 'hi'

type LongTailOverrides = {
    routeError: Partial<typeof enTranslations.routeError>
    pwa: Partial<typeof enTranslations.pwa>
    adminLayout: Partial<typeof enTranslations.adminLayout>
    favorites: Partial<typeof enTranslations.favorites>
    notifications: Partial<typeof enTranslations.notifications>
    [key: string]: unknown
}

export const longTailPopular = {
    es: {
        routeError: { title: 'Página no disponible', description: 'No se pudo cargar esta página. Recárgala e inténtalo de nuevo.', retry: 'Recargar página' },
        pwa: { offlineTitle: 'Sin conexión', offlineDescription: 'Algunos datos no estarán disponibles hasta que vuelva la conexión.', updateTitle: 'Nueva versión disponible', updateDescription: 'Recarga para usar la última versión de AutoCare Hub.', updateBlockedDescription: 'Termina o guarda el trabajo activo antes de actualizar.', updateFailedDescription: 'No se pudo aplicar la actualización. Inténtalo de nuevo.', updateAction: 'Actualizar', updateProgress: 'Actualizando...', offlineReadyTitle: 'Listo para usar sin conexión', offlineReadyDescription: 'La aplicación está disponible sin conexión.' },
        commission: { eyebrow: 'Precios sencillos para propietarios', title: 'Sin suscripción mensual', description: 'AutoCare Hub solo gana cuando tu espacio gana.', perBooking: 'de cada reserva completada', mainDescription: 'Se aplica una comisión transparente del 2% a las reservas online pagadas. No hay cuota mensual ni comisión por reservas canceladas o impagadas.', ownerAction: 'Abrir espacio del propietario', includesTitle: 'Qué incluye', featureNoSubscription: 'Sin pagos de suscripción recurrentes', featureSuccessfulOnly: 'La comisión se aplica solo a reservas pagadas', featureTransparent: 'La comisión se muestra antes del pago', featurePayouts: 'El importe restante se prepara para el pago al propietario' },
        adminLayout: { title: 'Moderación y gestión de la plataforma' },
        favorites: { eyebrow: 'Favoritos', title: 'Espacios guardados', description: 'Guarda espacios interesantes y vuelve a ellos cuando quieras reservar.', emptyTitle: 'Todavía no hay espacios guardados', emptyDescription: 'Pulsa el corazón de una tarjeta para guardarla aquí.', openCatalog: 'Abrir catálogo', openCabinet: 'Abrir espacio', remove: 'Quitar de favoritos' },
        notifications: { eyebrow: 'Notificaciones', title: 'Actualizaciones de reservas', description: 'Aquí se reúnen los eventos importantes de reservas y de la cuenta.', unreadCount: '{{count}} sin leer', unread: 'Sin leer', markRead: 'Marcar como leída', markAllRead: 'Marcar todas como leídas', markingRead: 'Marcando...', loadMore: 'Cargar más', loadingMore: 'Cargando más...', emptyTitle: 'Aún no hay notificaciones', emptyDescription: 'Aquí aparecerán cambios de reservas, moderación y cuenta.', open: 'Abrir', managePreferences: 'Gestionar preferencias', updateError: 'No se pudieron actualizar las notificaciones. Inténtalo de nuevo.' },
    },
    de: {
        routeError: { title: 'Seite nicht verfügbar', description: 'Diese Seite konnte nicht geladen werden. Lade sie neu und versuche es erneut.', retry: 'Seite neu laden' },
        pwa: { offlineTitle: 'Du bist offline', offlineDescription: 'Einige Daten sind erst wieder verfügbar, wenn die Verbindung zurück ist.', updateTitle: 'Neue Version verfügbar', updateDescription: 'Lade die Seite neu, um die aktuelle AutoCare Hub-Version zu verwenden.', updateBlockedDescription: 'Schließe die aktive Arbeit ab oder speichere sie vor dem Update.', updateFailedDescription: 'Das Update konnte nicht angewendet werden. Versuche es erneut.', updateAction: 'Aktualisieren', updateProgress: 'Wird aktualisiert...', offlineReadyTitle: 'Offline bereit', offlineReadyDescription: 'Die App-Oberfläche ist ohne Verbindung verfügbar.' },
        commission: { eyebrow: 'Einfache Preise für Eigentümer', title: 'Kein monatliches Abo', description: 'AutoCare Hub verdient nur, wenn dein Raum verdient.', perBooking: 'jeder erfolgreichen Buchung', mainDescription: 'Für erfolgreiche Online-Buchungen gilt eine transparente Provision von 2 %. Es gibt keine monatliche Gebühr und keine Kosten für stornierte oder unbezahlte Buchungen.', ownerAction: 'Eigentümerbereich öffnen', includesTitle: 'Enthalten', featureNoSubscription: 'Keine wiederkehrende Abonnementgebühr', featureSuccessfulOnly: 'Provision nur für bezahlte Buchungen', featureTransparent: 'Die Provision wird vor der Zahlung angezeigt', featurePayouts: 'Der Restbetrag wird für die Auszahlung vorbereitet' },
        adminLayout: { title: 'Moderation und Plattformverwaltung' },
        favorites: { eyebrow: 'Favoriten', title: 'Gespeicherte Räume', description: 'Behalte interessante Räume im Blick und kehre zum Buchen zurück.', emptyTitle: 'Noch keine Räume gespeichert', emptyDescription: 'Klicke auf das Herz einer Karte, um sie hier zu speichern.', openCatalog: 'Katalog öffnen', openCabinet: 'Raum öffnen', remove: 'Aus Favoriten entfernen' },
        notifications: { eyebrow: 'Benachrichtigungen', title: 'Buchungsupdates', description: 'Wichtige Ereignisse zu Buchungen und Konto werden hier gesammelt.', unreadCount: '{{count}} ungelesen', unread: 'Ungelesen', markRead: 'Als gelesen markieren', markAllRead: 'Alle als gelesen markieren', markingRead: 'Wird markiert...', loadMore: 'Mehr laden', loadingMore: 'Weitere werden geladen...', emptyTitle: 'Noch keine Benachrichtigungen', emptyDescription: 'Änderungen zu Buchungen, Moderation und Konto erscheinen hier.', open: 'Öffnen', managePreferences: 'Einstellungen verwalten', updateError: 'Benachrichtigungen konnten nicht aktualisiert werden. Versuche es erneut.' },
    },
    fr: {
        routeError: { title: 'Page indisponible', description: 'Cette page n’a pas pu être chargée. Rechargez-la puis réessayez.', retry: 'Recharger la page' },
        pwa: { offlineTitle: 'Vous êtes hors connexion', offlineDescription: 'Certaines données seront indisponibles jusqu’au retour de la connexion.', updateTitle: 'Nouvelle version disponible', updateDescription: 'Rechargez pour utiliser la dernière version de AutoCare Hub.', updateBlockedDescription: 'Terminez ou enregistrez le travail en cours avant la mise à jour.', updateFailedDescription: 'La mise à jour n’a pas pu être appliquée. Réessayez.', updateAction: 'Mettre à jour', updateProgress: 'Mise à jour...', offlineReadyTitle: 'Prêt hors connexion', offlineReadyDescription: 'L’interface de l’application est disponible sans connexion.' },
        commission: { eyebrow: 'Tarification simple pour les propriétaires', title: 'Sans abonnement mensuel', description: 'AutoCare Hub gagne uniquement quand votre espace gagne.', perBooking: 'de chaque réservation réussie', mainDescription: 'Une commission transparente de 2 % s’applique aux réservations en ligne payées. Il n’y a ni frais mensuels ni frais pour les réservations annulées ou impayées.', ownerAction: 'Ouvrir l’espace propriétaire', includesTitle: 'Ce qui est inclus', featureNoSubscription: 'Aucun paiement d’abonnement récurrent', featureSuccessfulOnly: 'Commission uniquement sur les réservations payées', featureTransparent: 'La commission est affichée avant le paiement', featurePayouts: 'Le solde est préparé pour le versement au propriétaire' },
        adminLayout: { title: 'Modération et gestion de la plateforme' },
        favorites: { eyebrow: 'Favoris', title: 'Espaces enregistrés', description: 'Gardez les espaces intéressants à portée de main avant de réserver.', emptyTitle: 'Aucun espace enregistré', emptyDescription: 'Touchez le cœur d’une carte pour l’enregistrer ici.', openCatalog: 'Ouvrir le catalogue', openCabinet: 'Ouvrir l’espace', remove: 'Retirer des favoris' },
        notifications: { eyebrow: 'Notifications', title: 'Mises à jour des réservations', description: 'Les événements importants liés aux réservations et au compte sont regroupés ici.', unreadCount: '{{count}} non lue(s)', unread: 'Non lue', markRead: 'Marquer comme lue', markAllRead: 'Tout marquer comme lu', markingRead: 'Marquage...', loadMore: 'Charger plus', loadingMore: 'Chargement...', emptyTitle: 'Aucune notification', emptyDescription: 'Les changements de réservation, de modération et de compte apparaîtront ici.', open: 'Ouvrir', managePreferences: 'Gérer les préférences', updateError: 'Impossible de mettre à jour les notifications. Réessayez.' },
    },
    pt: {
        routeError: { title: 'Página indisponível', description: 'Não foi possível carregar esta página. Recarregue e tente novamente.', retry: 'Recarregar página' },
        pwa: { offlineTitle: 'Você está offline', offlineDescription: 'Alguns dados podem ficar indisponíveis até a conexão voltar.', updateTitle: 'Nova versão disponível', updateDescription: 'Recarregue para usar a versão mais recente do AutoCare Hub.', updateBlockedDescription: 'Conclua ou salve o trabalho ativo antes de atualizar.', updateFailedDescription: 'Não foi possível aplicar a atualização. Tente novamente.', updateAction: 'Atualizar', updateProgress: 'Atualizando...', offlineReadyTitle: 'Pronto para uso offline', offlineReadyDescription: 'A interface do app está disponível sem conexão.' },
        commission: { eyebrow: 'Preços simples para proprietários', title: 'Sem assinatura mensal', description: 'O AutoCare Hub ganha apenas quando o seu espaço ganha.', perBooking: 'de cada reserva concluída', mainDescription: 'Uma comissão transparente de 2% é aplicada às reservas online pagas. Não há mensalidade nem cobrança por reservas canceladas ou não pagas.', ownerAction: 'Abrir espaço do proprietário', includesTitle: 'O que está incluído', featureNoSubscription: 'Sem pagamento recorrente de assinatura', featureSuccessfulOnly: 'Comissão apenas sobre reservas pagas', featureTransparent: 'A comissão aparece antes do pagamento', featurePayouts: 'O valor restante é preparado para repasse ao proprietário' },
        adminLayout: { title: 'Moderação e gestão da plataforma' },
        favorites: { eyebrow: 'Favoritos', title: 'Espaços salvos', description: 'Guarde espaços interessantes e volte quando estiver pronto para reservar.', emptyTitle: 'Nenhum espaço salvo ainda', emptyDescription: 'Toque no coração de um cartão para salvá-lo aqui.', openCatalog: 'Abrir catálogo', openCabinet: 'Abrir espaço', remove: 'Remover dos favoritos' },
        notifications: { eyebrow: 'Notificações', title: 'Atualizações de reservas', description: 'Eventos importantes de reservas e da conta ficam reunidos aqui.', unreadCount: '{{count}} não lida(s)', unread: 'Não lida', markRead: 'Marcar como lida', markAllRead: 'Marcar todas como lidas', markingRead: 'Marcando...', loadMore: 'Carregar mais', loadingMore: 'Carregando mais...', emptyTitle: 'Nenhuma notificação ainda', emptyDescription: 'Atualizações de reservas, moderação e conta aparecerão aqui.', open: 'Abrir', managePreferences: 'Gerenciar preferências', updateError: 'Não foi possível atualizar as notificações. Tente novamente.' },
    },
    zh: {
        routeError: { title: '页面不可用', description: '无法加载此页面。请重新加载后再试。', retry: '重新加载页面' },
        pwa: { offlineTitle: '当前处于离线状态', offlineDescription: '连接恢复前，部分数据可能无法使用。', updateTitle: '有新版本可用', updateDescription: '重新加载以使用最新版本的 AutoCare Hub。', updateBlockedDescription: '更新前请完成或保存当前操作。', updateFailedDescription: '无法应用更新，请重试。', updateAction: '更新', updateProgress: '正在更新...', offlineReadyTitle: '已准备好离线使用', offlineReadyDescription: '应用界面无需连接也可以使用。' },
        commission: { eyebrow: '面向房主的简单定价', title: '无月度订阅费', description: '只有当您的空间产生收益时，AutoCare Hub 才会收费。', perBooking: '每笔成功预订', mainDescription: '已支付的在线预订收取透明的 2% 佣金。不收月费，取消或未支付的预订也不收费。', ownerAction: '打开房主工作台', includesTitle: '包含内容', featureNoSubscription: '没有重复订阅费用', featureSuccessfulOnly: '仅对已支付预订收取佣金', featureTransparent: '付款前显示佣金', featurePayouts: '剩余金额将准备支付给房主' },
        adminLayout: { title: '平台审核与管理' },
        favorites: { eyebrow: '收藏', title: '已保存的空间', description: '保存感兴趣的空间，准备预订时再回来。', emptyTitle: '还没有保存的空间', emptyDescription: '点击空间卡片上的心形图标即可保存。', openCatalog: '打开目录', openCabinet: '打开空间', remove: '取消收藏' },
        notifications: { eyebrow: '通知', title: '预订更新', description: '重要的预订和账户事件会集中显示在这里。', unreadCount: '{{count}} 条未读', unread: '未读', markRead: '标记为已读', markAllRead: '全部标记为已读', markingRead: '正在标记...', loadMore: '加载更多', loadingMore: '正在加载更多...', emptyTitle: '暂无通知', emptyDescription: '预订、审核和账户更新会在发生变化时显示在这里。', open: '打开', managePreferences: '管理偏好设置', updateError: '无法更新通知，请重试。' },
    },
    ja: {
        routeError: { title: 'ページを利用できません', description: 'ページを読み込めませんでした。再読み込みしてもう一度お試しください。', retry: 'ページを再読み込み' },
        pwa: { offlineTitle: 'オフラインです', offlineDescription: '接続が戻るまで一部のデータを利用できない場合があります。', updateTitle: '新しいバージョンがあります', updateDescription: '再読み込みして最新のAutoCare Hubを使用してください。', updateBlockedDescription: '更新前に作業を完了するか保存してください。', updateFailedDescription: '更新を適用できませんでした。もう一度お試しください。', updateAction: '更新', updateProgress: '更新中...', offlineReadyTitle: 'オフライン利用の準備完了', offlineReadyDescription: 'アプリの基本画面は接続なしでも利用できます。' },
        commission: { eyebrow: 'オーナー向けのシンプルな料金', title: '月額サブスクリプションなし', description: 'AutoCare Hubはスペースの収益が発生したときだけ手数料を受け取ります。', perBooking: '成功した予約ごとに', mainDescription: '支払い済みのオンライン予約に透明な2%の手数料が適用されます。月額料金やキャンセル・未払い予約の料金はありません。', ownerAction: 'オーナー画面を開く', includesTitle: '含まれる内容', featureNoSubscription: '継続的なサブスクリプション料金なし', featureSuccessfulOnly: '支払い済み予約のみ手数料の対象', featureTransparent: '支払い前に手数料を表示', featurePayouts: '残額をオーナーへの支払い用に準備' },
        adminLayout: { title: 'モデレーションとプラットフォーム管理' },
        favorites: { eyebrow: 'お気に入り', title: '保存したスペース', description: '気になるスペースを保存して、予約するときに戻れます。', emptyTitle: '保存したスペースはありません', emptyDescription: 'スペースカードのハートを押すとここに保存できます。', openCatalog: 'カタログを開く', openCabinet: 'スペースを開く', remove: 'お気に入りから削除' },
        notifications: { eyebrow: '通知', title: '予約の更新', description: '予約とアカウントに関する重要なイベントをここで確認できます。', unreadCount: '{{count}}件未読', unread: '未読', markRead: '既読にする', markAllRead: 'すべて既読にする', markingRead: '処理中...', loadMore: 'さらに読み込む', loadingMore: '読み込み中...', emptyTitle: '通知はありません', emptyDescription: '予約、モデレーション、アカウントの更新がここに表示されます。', open: '開く', managePreferences: '設定を管理', updateError: '通知を更新できませんでした。もう一度お試しください。' },
    },
    ko: {
        routeError: { title: '페이지를 사용할 수 없습니다', description: '페이지를 불러오지 못했습니다. 새로고침 후 다시 시도하세요.', retry: '페이지 새로고침' },
        pwa: { offlineTitle: '오프라인 상태입니다', offlineDescription: '연결이 복구될 때까지 일부 데이터를 사용할 수 없습니다.', updateTitle: '새 버전을 사용할 수 있습니다', updateDescription: '새로고침하여 최신 AutoCare Hub를 사용하세요.', updateBlockedDescription: '업데이트 전에 진행 중인 작업을 완료하거나 저장하세요.', updateFailedDescription: '업데이트를 적용하지 못했습니다. 다시 시도하세요.', updateAction: '업데이트', updateProgress: '업데이트 중...', offlineReadyTitle: '오프라인 사용 준비 완료', offlineReadyDescription: '앱 화면은 연결 없이도 사용할 수 있습니다.' },
        commission: { eyebrow: '소유자를 위한 간단한 요금', title: '월간 구독 없음', description: 'AutoCare Hub는 공간에 수익이 발생할 때만 수익을 얻습니다.', perBooking: '성공한 예약마다', mainDescription: '결제된 온라인 예약에 투명한 2% 수수료가 적용됩니다. 월 이용료와 취소 또는 미결제 예약 수수료는 없습니다.', ownerAction: '소유자 워크스페이스 열기', includesTitle: '포함 내용', featureNoSubscription: '반복 구독 결제 없음', featureSuccessfulOnly: '결제된 예약에만 수수료 적용', featureTransparent: '결제 전에 수수료 표시', featurePayouts: '남은 금액을 소유자 지급용으로 준비' },
        adminLayout: { title: '검토 및 플랫폼 관리' },
        favorites: { eyebrow: '즐겨찾기', title: '저장한 공간', description: '관심 있는 공간을 저장하고 예약할 때 다시 확인하세요.', emptyTitle: '저장한 공간이 없습니다', emptyDescription: '공간 카드의 하트를 눌러 여기에 저장하세요.', openCatalog: '카탈로그 열기', openCabinet: '공간 열기', remove: '즐겨찾기에서 삭제' },
        notifications: { eyebrow: '알림', title: '예약 업데이트', description: '예약과 계정의 중요한 이벤트를 여기에서 확인할 수 있습니다.', unreadCount: '{{count}}개 읽지 않음', unread: '읽지 않음', markRead: '읽음으로 표시', markAllRead: '모두 읽음으로 표시', markingRead: '표시 중...', loadMore: '더 불러오기', loadingMore: '더 불러오는 중...', emptyTitle: '알림이 없습니다', emptyDescription: '예약, 검토, 계정 변경 사항이 여기 표시됩니다.', open: '열기', managePreferences: '환경설정 관리', updateError: '알림을 업데이트하지 못했습니다. 다시 시도하세요.' },
    },
    ar: {
        routeError: { title: 'الصفحة غير متاحة', description: 'تعذر تحميل هذه الصفحة. أعد تحميلها وحاول مرة أخرى.', retry: 'إعادة تحميل الصفحة' },
        pwa: { offlineTitle: 'أنت غير متصل', offlineDescription: 'قد لا تتوفر بعض البيانات حتى يعود الاتصال.', updateTitle: 'يتوفر إصدار جديد', updateDescription: 'أعد التحميل لاستخدام أحدث إصدار من AutoCare Hub.', updateBlockedDescription: 'أكمل العمل النشط أو احفظه قبل التحديث.', updateFailedDescription: 'تعذر تطبيق التحديث. حاول مرة أخرى.', updateAction: 'تحديث', updateProgress: 'جارٍ التحديث...', offlineReadyTitle: 'جاهز للاستخدام دون اتصال', offlineReadyDescription: 'واجهة التطبيق متاحة دون اتصال.' },
        commission: { eyebrow: 'تسعير بسيط للمالكين', title: 'من دون اشتراك شهري', description: 'تحصل AutoCare Hub على عائد فقط عندما يحقق مساحتك عائدًا.', perBooking: 'من كل حجز ناجح', mainDescription: 'تُطبق عمولة شفافة بنسبة 2% على الحجوزات الإلكترونية المدفوعة. لا توجد رسوم شهرية ولا رسوم على الحجوزات الملغاة أو غير المدفوعة.', ownerAction: 'فتح مساحة المالك', includesTitle: 'ما الذي يتضمنه', featureNoSubscription: 'لا توجد دفعات اشتراك متكررة', featureSuccessfulOnly: 'تُطبق العمولة على الحجوزات المدفوعة فقط', featureTransparent: 'تظهر العمولة قبل الدفع', featurePayouts: 'يُجهز المبلغ المتبقي للدفع إلى المالك' },
        adminLayout: { title: 'الإشراف وإدارة المنصة' },
        favorites: { eyebrow: 'المفضلة', title: 'المساحات المحفوظة', description: 'احتفظ بالمساحات المناسبة وعد إليها عندما تستعد للحجز.', emptyTitle: 'لا توجد مساحات محفوظة بعد', emptyDescription: 'اضغط على القلب في بطاقة المساحة لحفظها هنا.', openCatalog: 'فتح الكتالوج', openCabinet: 'فتح المساحة', remove: 'إزالة من المفضلة' },
        notifications: { eyebrow: 'الإشعارات', title: 'تحديثات الحجوزات', description: 'تُجمع هنا الأحداث المهمة المتعلقة بالحجوزات والحساب.', unreadCount: '{{count}} غير مقروء', unread: 'غير مقروء', markRead: 'تحديد كمقروء', markAllRead: 'تحديد الكل كمقروء', markingRead: 'جارٍ التحديد...', loadMore: 'تحميل المزيد', loadingMore: 'جارٍ تحميل المزيد...', emptyTitle: 'لا توجد إشعارات بعد', emptyDescription: 'ستظهر هنا تحديثات الحجوزات والإشراف والحساب عند حدوثها.', open: 'فتح', managePreferences: 'إدارة التفضيلات', updateError: 'تعذر تحديث الإشعارات. حاول مرة أخرى.' },
    },
    tr: {
        routeError: { title: 'Sayfa kullanılamıyor', description: 'Bu sayfa yüklenemedi. Yenileyip tekrar deneyin.', retry: 'Sayfayı yenile' },
        pwa: { offlineTitle: 'Çevrimdışısınız', offlineDescription: 'Bağlantı yeniden kurulana kadar bazı veriler kullanılamayabilir.', updateTitle: 'Yeni sürüm mevcut', updateDescription: 'AutoCare Hub’nun en son sürümünü kullanmak için yenileyin.', updateBlockedDescription: 'Güncellemeden önce etkin çalışmayı tamamlayın veya kaydedin.', updateFailedDescription: 'Güncelleme uygulanamadı. Tekrar deneyin.', updateAction: 'Güncelle', updateProgress: 'Güncelleniyor...', offlineReadyTitle: 'Çevrimdışı kullanıma hazır', offlineReadyDescription: 'Uygulama arayüzü bağlantı olmadan kullanılabilir.' },
        commission: { eyebrow: 'Sahipler için basit fiyatlandırma', title: 'Aylık abonelik yok', description: 'AutoCare Hub yalnızca alanınız kazandığında kazanır.', perBooking: 'başarılı her rezervasyondan', mainDescription: 'Ödenmiş çevrimiçi rezervasyonlara şeffaf %2 komisyon uygulanır. Aylık ücret ve iptal edilen veya ödenmeyen rezervasyonlar için ücret yoktur.', ownerAction: 'Sahip çalışma alanını aç', includesTitle: 'Neler dahil', featureNoSubscription: 'Tekrarlanan abonelik ödemesi yok', featureSuccessfulOnly: 'Komisyon yalnızca ödenmiş rezervasyonlara uygulanır', featureTransparent: 'Komisyon ödeme öncesinde gösterilir', featurePayouts: 'Kalan tutar sahibine ödeme için hazırlanır' },
        adminLayout: { title: 'Moderasyon ve platform yönetimi' },
        favorites: { eyebrow: 'Favoriler', title: 'Kaydedilen alanlar', description: 'İlginizi çeken alanları kaydedin ve rezervasyon zamanı geri dönün.', emptyTitle: 'Henüz kaydedilen alan yok', emptyDescription: 'Buraya kaydetmek için karttaki kalbe dokunun.', openCatalog: 'Kataloğu aç', openCabinet: 'Alanı aç', remove: 'Favorilerden kaldır' },
        notifications: { eyebrow: 'Bildirimler', title: 'Rezervasyon güncellemeleri', description: 'Rezervasyon ve hesapla ilgili önemli olaylar burada toplanır.', unreadCount: '{{count}} okunmamış', unread: 'Okunmamış', markRead: 'Okundu olarak işaretle', markAllRead: 'Tümünü okundu işaretle', markingRead: 'İşaretleniyor...', loadMore: 'Daha fazla yükle', loadingMore: 'Daha fazla yükleniyor...', emptyTitle: 'Henüz bildirim yok', emptyDescription: 'Rezervasyon, moderasyon ve hesap güncellemeleri burada görünür.', open: 'Aç', managePreferences: 'Tercihleri yönet', updateError: 'Bildirimler güncellenemedi. Tekrar deneyin.' },
    },
    hi: {
        routeError: { title: 'पेज उपलब्ध नहीं है', description: 'यह पेज लोड नहीं हो सका। इसे रीलोड करके फिर कोशिश करें।', retry: 'पेज रीलोड करें' },
        pwa: { offlineTitle: 'आप ऑफलाइन हैं', offlineDescription: 'कनेक्शन वापस आने तक कुछ डेटा उपलब्ध नहीं हो सकता।', updateTitle: 'नया संस्करण उपलब्ध है', updateDescription: 'AutoCare Hub का नवीनतम संस्करण इस्तेमाल करने के लिए रीलोड करें।', updateBlockedDescription: 'अपडेट से पहले सक्रिय काम पूरा करें या सेव करें।', updateFailedDescription: 'अपडेट लागू नहीं हो सका। फिर कोशिश करें।', updateAction: 'अपडेट करें', updateProgress: 'अपडेट हो रहा है...', offlineReadyTitle: 'ऑफलाइन इस्तेमाल के लिए तैयार', offlineReadyDescription: 'ऐप इंटरफेस बिना कनेक्शन के उपलब्ध है।' },
        commission: { eyebrow: 'मालिकों के लिए सरल मूल्य', title: 'कोई मासिक सदस्यता नहीं', description: 'AutoCare Hub तभी कमाता है जब आपका स्थान कमाता है।', perBooking: 'हर सफल बुकिंग से', mainDescription: 'भुगतान की गई ऑनलाइन बुकिंग पर पारदर्शी 2% कमीशन लागू होता है। कोई मासिक शुल्क नहीं और रद्द या बिना भुगतान वाली बुकिंग पर कोई शुल्क नहीं।', ownerAction: 'मालिक वर्कस्पेस खोलें', includesTitle: 'क्या शामिल है', featureNoSubscription: 'कोई बार-बार सदस्यता भुगतान नहीं', featureSuccessfulOnly: 'कमीशन केवल भुगतान की गई बुकिंग पर', featureTransparent: 'भुगतान से पहले कमीशन दिखाया जाता है', featurePayouts: 'बाकी राशि मालिक को भुगतान के लिए तैयार की जाती है' },
        adminLayout: { title: 'मॉडरेशन और प्लेटफॉर्म प्रबंधन' },
        favorites: { eyebrow: 'पसंदीदा', title: 'सेव किए गए स्थान', description: 'पसंद आने वाले स्थान सेव करें और बुकिंग के समय वापस आएं।', emptyTitle: 'अभी कोई स्थान सेव नहीं है', emptyDescription: 'यहां सेव करने के लिए कार्ड पर दिल दबाएं।', openCatalog: 'कैटलॉग खोलें', openCabinet: 'स्थान खोलें', remove: 'पसंदीदा से हटाएं' },
        notifications: { eyebrow: 'सूचनाएं', title: 'बुकिंग अपडेट', description: 'बुकिंग और खाते से जुड़ी महत्वपूर्ण घटनाएं यहां दिखाई देती हैं।', unreadCount: '{{count}} अपठित', unread: 'अपठित', markRead: 'पढ़ा हुआ चिह्नित करें', markAllRead: 'सभी को पढ़ा हुआ चिह्नित करें', markingRead: 'चिह्नित हो रहा है...', loadMore: 'और लोड करें', loadingMore: 'और लोड हो रहा है...', emptyTitle: 'अभी कोई सूचना नहीं', emptyDescription: 'बुकिंग, मॉडरेशन और खाते के अपडेट यहां दिखाई देंगे।', open: 'खोलें', managePreferences: 'प्राथमिकताएं प्रबंधित करें', updateError: 'सूचनाएं अपडेट नहीं हो सकीं। फिर कोशिश करें।' },
    },
} satisfies Record<PopularLocale, LongTailOverrides>
