// Public compatibility facade. Use cases own authorization, transactions and response mapping.
export { getAutoCareLocationZones, getAutoCareMarkets, getAutoCareServiceDefinitions } from './catalog-read.service.js'
export { getAutoCareDiscovery } from './provider-discovery.service.js'
export { getAutoCareProviderOffers, getAutoCareProviderProfile, getOwnerAutoCareProviders } from './provider-read.service.js'
export { getAutoCareProviderReviews, getFeaturedAutoCareReviews, getMyAutoCareReviews, getOwnerAutoCareProviderReviews, getOwnerAutoCareReviews } from './provider-reviews-read.service.js'
export { createAutoCareReview, updateClientAutoCareReview } from './provider-reviews-write.service.js'
export { createOwnerAutoCareReviewPromo, redeemAutoCareReviewPromo } from './provider-review-promo.service.js'
export { createOwnerAutoCareProvider } from './provider-create.service.js'
export { createOwnerAutoCareCapacityResource, getOwnerAutoCareCapacityReservations, getOwnerAutoCareCapacityResources, updateOwnerAutoCareCapacityResource } from './provider-resources.service.js'
export type { AutoCareCapacityResourceInput, AutoCareCapacityResourcePatch } from './provider-resources.service.js'
export { updateOwnerAutoCareCommunicationSettings, updateOwnerAutoCareOffer } from './provider-workspace.service.js'
export { getAutoCareProviderLogo, saveAutoCareProviderLogo, saveAutoCareProviderMedia } from './provider-media.service.js'
