// Public compatibility facade. Use cases own authorization, transactions and response mapping.
export { assertAutoCareChatRealtimeAccess, ensureAutoCareRequestChatThread, getAutoCareChatAccessContext } from './chat-access.service.js'
export { createAutoCareChat, getAutoCareChat, getAutoCareChatThreadForRequest } from './chat-thread.service.js'
export { createAutoCareChatMessage, deleteAutoCareChatMessage, markAutoCareChatRead } from './chat-messaging.service.js'
export type { AutoCareChatBlockResponse, AutoCareChatReportResponse, CreateAutoCareChatReportInput } from './chat-moderation-response.js'
export { createAutoCareChatReport, decideAdminAutoCareChatReport, listAdminAutoCareChatReports, listMyAutoCareChatReports } from './chat-report.service.js'
export { assignAdminAutoCareChatModerator, extendAdminAutoCareChatModeratorAccess } from './chat-moderator-assignment.service.js'
export { createAutoCareChatBlock, revokeAutoCareChatBlock } from './chat-block.service.js'
export { createAutoCareChatAttachment, getAutoCareChatAttachment } from './chat-attachment.service.js'
export { getMyAutoCareChats } from './chat-read.service.js'
