import { BadgeCheck, MapPin, PauseCircle, Send, ShieldCheck } from 'lucide-react'

import { type AdminAutoCareProvider, ProviderLogo, useUpdateAdminAutoCareProviderStatusMutation } from '@/entities/automotive-service'

type AdminAutoCareModerationQueueProps = { locale: string; providers: AdminAutoCareProvider[] }
const copy = { en: { title: 'Provider moderation', description: 'Publish services only when the profile is complete and quality signals support it.', owner: 'Owner', trust: 'Trust index', publish: 'Publish', suspend: 'Suspend', draft: 'Return to draft', active: 'Active', pending: 'Draft', suspended: 'Suspended', empty: 'No provider profiles need moderation.' }, ru: { title: 'Модерация сервисов', description: 'Публикуйте сервис только если профиль заполнен и сигналы качества это подтверждают.', owner: 'Владелец', trust: 'Индекс доверия', publish: 'Опубликовать', suspend: 'Приостановить', draft: 'В черновик', active: 'Опубликован', pending: 'Черновик', suspended: 'Приостановлен', empty: 'Нет профилей, которые требуют модерации.' } }

function statusText(status: AdminAutoCareProvider['status'], text: typeof copy.en) { return status === 'active' ? text.active : status === 'draft' ? text.pending : text.suspended }

export function AdminAutoCareModerationQueue({ locale, providers }: AdminAutoCareModerationQueueProps) {
    const text = locale === 'ru' ? copy.ru : copy.en
    const [updateStatus, { isLoading }] = useUpdateAdminAutoCareProviderStatusMutation()
    const visible = [...providers].sort((a, b) => Number(a.status === 'draft') - Number(b.status === 'draft')).reverse().slice(0, 6)
    const changeStatus = (id: string, status: AdminAutoCareProvider['status']) => { void updateStatus({ id, status }) }
    return <section className="rounded-[var(--radius-panel)] border border-border bg-card p-5 shadow-sm"><div><h2 className="text-lg font-black text-foreground">{text.title}</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">{text.description}</p></div>{visible.length ? <div className="mt-5 divide-y divide-border">{visible.map((provider) => <article key={provider.id} className="flex flex-col gap-4 py-4 first:pt-0 lg:flex-row lg:items-center"><div className="flex min-w-0 flex-1 items-center gap-3"><ProviderLogo name={provider.name} logoUrl={provider.logoUrl} className="size-11" /><div className="min-w-0"><div className="flex items-center gap-1"><p className="truncate text-sm font-black text-foreground">{provider.name}</p>{provider.verified && <BadgeCheck className="size-4 shrink-0 text-primary" />}</div><p className="mt-1 flex items-center gap-1 truncate text-xs text-muted-foreground"><MapPin className="size-3" />{provider.location.address}</p><p className="mt-1 text-xs text-muted-foreground">{text.owner}: {provider.ownerName ?? '—'}</p></div></div><div className="flex shrink-0 items-center gap-4"><div className="text-right"><p className="text-[11px] font-bold uppercase tracking-wide text-muted-foreground">{text.trust}</p><p className="mt-1 text-sm font-black text-foreground">{provider.trustScore}/100</p><p className="mt-1 text-[11px] font-bold text-primary">{statusText(provider.status, text)}</p></div>{provider.status === 'draft' ? <button type="button" disabled={isLoading} onClick={() => changeStatus(provider.id, 'active')} className="inline-flex h-9 items-center gap-1.5 rounded-[var(--radius-control)] bg-primary px-3 text-xs font-black text-primary-foreground"><Send className="size-3.5" />{text.publish}</button> : provider.status === 'active' ? <button type="button" disabled={isLoading} onClick={() => changeStatus(provider.id, 'suspended')} className="inline-flex h-9 items-center gap-1.5 rounded-[var(--radius-control)] border border-border px-3 text-xs font-black text-foreground hover:border-destructive hover:text-destructive"><PauseCircle className="size-3.5" />{text.suspend}</button> : <button type="button" disabled={isLoading} onClick={() => changeStatus(provider.id, 'draft')} className="inline-flex h-9 items-center gap-1.5 rounded-[var(--radius-control)] border border-border px-3 text-xs font-black text-foreground"><ShieldCheck className="size-3.5" />{text.draft}</button>}</div></article>)}</div> : <p className="mt-5 rounded-[var(--radius-card)] bg-secondary p-4 text-sm text-muted-foreground">{text.empty}</p>}</section>
}
