import { enTranslations } from './en.js'

type DeepPartial<T> = {
    [Key in keyof T]?: T[Key] extends object ? DeepPartial<T[Key]> : T[Key]
}

type LocaleOverrides = {
    common?: Partial<typeof enTranslations.common>
    navigation?: Partial<typeof enTranslations.navigation>
    errors?: Partial<typeof enTranslations.errors>
    notifications?: DeepPartial<typeof enTranslations.notifications>
    emails?: DeepPartial<typeof enTranslations.emails>
}

function mergeSection<T extends object>(
    base: T,
    override: DeepPartial<T> | undefined,
): T {
    return { ...base, ...override } as T
}

function createPopularLocale(overrides: LocaleOverrides): typeof enTranslations {
    return {
        ...enTranslations,
        common: mergeSection(enTranslations.common, overrides.common),
        navigation: mergeSection(enTranslations.navigation, overrides.navigation),
        errors: mergeSection(enTranslations.errors, overrides.errors),
        notifications: {
            ...enTranslations.notifications,
            security: mergeSection(
                enTranslations.notifications.security,
                overrides.notifications?.security,
            ),
            payment: mergeSection(
                enTranslations.notifications.payment,
                overrides.notifications?.payment,
            ),
        } as typeof enTranslations.notifications,
        emails: {
            ...enTranslations.emails,
            common: mergeSection(enTranslations.emails.common, overrides.emails?.common),
            booking: mergeSection(enTranslations.emails.booking, overrides.emails?.booking),
            passwordSetup: mergeSection(enTranslations.emails.passwordSetup, overrides.emails?.passwordSetup),
            passwordReset: mergeSection(enTranslations.emails.passwordReset, overrides.emails?.passwordReset),
            emailVerification: mergeSection(enTranslations.emails.emailVerification, overrides.emails?.emailVerification),
        } as typeof enTranslations.emails,
    }
}

const common = {
    es: { loading: 'Cargando...', loadingPage: 'Cargando página...', error: 'Error', failedToLoad: 'No se pudo cargar.', create: 'Crear', edit: 'Editar', delete: 'Eliminar', cancel: 'Cancelar', confirm: 'Confirmar', save: 'Guardar', back: 'Atrás', status: 'Estado', actions: 'Acciones', name: 'Nombre', email: 'Correo electrónico', saving: 'Guardando...', close: 'Cerrar', system: 'Sistema', language: 'Idioma', theme: 'Tema', tryAgainLater: 'Inténtalo de nuevo más tarde.' },
    de: { loading: 'Wird geladen...', loadingPage: 'Seite wird geladen...', error: 'Fehler', failedToLoad: 'Laden fehlgeschlagen.', create: 'Erstellen', edit: 'Bearbeiten', delete: 'Löschen', cancel: 'Abbrechen', confirm: 'Bestätigen', save: 'Speichern', back: 'Zurück', status: 'Status', actions: 'Aktionen', name: 'Name', email: 'E-Mail', saving: 'Wird gespeichert...', close: 'Schließen', system: 'System', language: 'Sprache', theme: 'Darstellung', tryAgainLater: 'Bitte später erneut versuchen.' },
    fr: { loading: 'Chargement...', loadingPage: 'Chargement de la page...', error: 'Erreur', failedToLoad: 'Impossible de charger.', create: 'Créer', edit: 'Modifier', delete: 'Supprimer', cancel: 'Annuler', confirm: 'Confirmer', save: 'Enregistrer', back: 'Retour', status: 'Statut', actions: 'Actions', name: 'Nom', email: 'E-mail', saving: 'Enregistrement...', close: 'Fermer', system: 'Système', language: 'Langue', theme: 'Thème', tryAgainLater: 'Veuillez réessayer plus tard.' },
    pt: { loading: 'Carregando...', loadingPage: 'Carregando página...', error: 'Erro', failedToLoad: 'Não foi possível carregar.', create: 'Criar', edit: 'Editar', delete: 'Excluir', cancel: 'Cancelar', confirm: 'Confirmar', save: 'Salvar', back: 'Voltar', status: 'Status', actions: 'Ações', name: 'Nome', email: 'E-mail', saving: 'Salvando...', close: 'Fechar', system: 'Sistema', language: 'Idioma', theme: 'Tema', tryAgainLater: 'Tente novamente mais tarde.' },
    zh: { loading: '正在加载...', loadingPage: '正在加载页面...', error: '错误', failedToLoad: '加载失败。', create: '创建', edit: '编辑', delete: '删除', cancel: '取消', confirm: '确认', save: '保存', back: '返回', status: '状态', actions: '操作', name: '姓名', email: '电子邮箱', saving: '正在保存...', close: '关闭', system: '系统', language: '语言', theme: '主题', tryAgainLater: '请稍后重试。' },
    ja: { loading: '読み込み中...', loadingPage: 'ページを読み込み中...', error: 'エラー', failedToLoad: '読み込めませんでした。', create: '作成', edit: '編集', delete: '削除', cancel: 'キャンセル', confirm: '確認', save: '保存', back: '戻る', status: 'ステータス', actions: '操作', name: '名前', email: 'メールアドレス', saving: '保存中...', close: '閉じる', system: 'システム', language: '言語', theme: 'テーマ', tryAgainLater: '後でもう一度お試しください。' },
    ko: { loading: '로드 중...', loadingPage: '페이지를 불러오는 중...', error: '오류', failedToLoad: '불러오지 못했습니다.', create: '생성', edit: '수정', delete: '삭제', cancel: '취소', confirm: '확인', save: '저장', back: '뒤로', status: '상태', actions: '작업', name: '이름', email: '이메일', saving: '저장 중...', close: '닫기', system: '시스템', language: '언어', theme: '테마', tryAgainLater: '나중에 다시 시도해 주세요.' },
    ar: { loading: 'جار التحميل...', loadingPage: 'جار تحميل الصفحة...', error: 'خطأ', failedToLoad: 'تعذر التحميل.', create: 'إنشاء', edit: 'تعديل', delete: 'حذف', cancel: 'إلغاء', confirm: 'تأكيد', save: 'حفظ', back: 'رجوع', status: 'الحالة', actions: 'الإجراءات', name: 'الاسم', email: 'البريد الإلكتروني', saving: 'جار الحفظ...', close: 'إغلاق', system: 'النظام', language: 'اللغة', theme: 'المظهر', tryAgainLater: 'يرجى المحاولة لاحقًا.' },
    tr: { loading: 'Yükleniyor...', loadingPage: 'Sayfa yükleniyor...', error: 'Hata', failedToLoad: 'Yüklenemedi.', create: 'Oluştur', edit: 'Düzenle', delete: 'Sil', cancel: 'İptal', confirm: 'Onayla', save: 'Kaydet', back: 'Geri', status: 'Durum', actions: 'İşlemler', name: 'Ad', email: 'E-posta', saving: 'Kaydediliyor...', close: 'Kapat', system: 'Sistem', language: 'Dil', theme: 'Tema', tryAgainLater: 'Lütfen daha sonra tekrar deneyin.' },
    hi: { loading: 'लोड हो रहा है...', loadingPage: 'पेज लोड हो रहा है...', error: 'त्रुटि', failedToLoad: 'लोड नहीं हो सका।', create: 'बनाएं', edit: 'संपादित करें', delete: 'हटाएं', cancel: 'रद्द करें', confirm: 'पुष्टि करें', save: 'सहेजें', back: 'वापस', status: 'स्थिति', actions: 'कार्रवाई', name: 'नाम', email: 'ईमेल', saving: 'सहेजा जा रहा है...', close: 'बंद करें', system: 'सिस्टम', language: 'भाषा', theme: 'थीम', tryAgainLater: 'कृपया बाद में फिर प्रयास करें।' },
} as const

const navigation = {
    es: { home: 'Inicio', cabinets: 'Cabinetes', profile: 'Perfil', myBookings: 'Mis reservas', ownerDashboard: 'Panel del propietario', ownerCabinets: 'Mis cabinetes', ownerBookings: 'Reservas', ownerServices: 'Servicios', adminDashboard: 'Panel de administración', adminUsers: 'Usuarios', adminOwners: 'Propietarios', adminCabinets: 'Cabinetes', adminReviews: 'Reseñas', adminAuditLogs: 'Registros de auditoría' },
    de: { home: 'Startseite', cabinets: 'Räume', profile: 'Profil', myBookings: 'Meine Buchungen', ownerDashboard: 'Eigentümer-Dashboard', ownerCabinets: 'Meine Räume', ownerBookings: 'Buchungen', ownerServices: 'Leistungen', adminDashboard: 'Admin-Dashboard', adminUsers: 'Benutzer', adminOwners: 'Eigentümer', adminCabinets: 'Räume', adminReviews: 'Bewertungen', adminAuditLogs: 'Audit-Protokolle' },
    fr: { home: 'Accueil', cabinets: 'Cabinets', profile: 'Profil', myBookings: 'Mes réservations', ownerDashboard: 'Tableau de bord propriétaire', ownerCabinets: 'Mes cabinets', ownerBookings: 'Réservations', ownerServices: 'Services', adminDashboard: 'Tableau de bord admin', adminUsers: 'Utilisateurs', adminOwners: 'Propriétaires', adminCabinets: 'Cabinets', adminReviews: 'Avis', adminAuditLogs: 'Journaux d’audit' },
    pt: { home: 'Início', cabinets: 'Salas', profile: 'Perfil', myBookings: 'Minhas reservas', ownerDashboard: 'Painel do proprietário', ownerCabinets: 'Minhas salas', ownerBookings: 'Reservas', ownerServices: 'Serviços', adminDashboard: 'Painel administrativo', adminUsers: 'Usuários', adminOwners: 'Proprietários', adminCabinets: 'Salas', adminReviews: 'Avaliações', adminAuditLogs: 'Logs de auditoria' },
    zh: { home: '首页', cabinets: '房间', profile: '个人资料', myBookings: '我的预订', ownerDashboard: '房主工作台', ownerCabinets: '我的房间', ownerBookings: '预订', ownerServices: '服务', adminDashboard: '管理后台', adminUsers: '用户', adminOwners: '房主', adminCabinets: '房间', adminReviews: '评价', adminAuditLogs: '审计日志' },
    ja: { home: 'ホーム', cabinets: 'キャビネット', profile: 'プロフィール', myBookings: '予約一覧', ownerDashboard: 'オーナーダッシュボード', ownerCabinets: 'マイキャビネット', ownerBookings: '予約', ownerServices: 'サービス', adminDashboard: '管理ダッシュボード', adminUsers: 'ユーザー', adminOwners: 'オーナー', adminCabinets: 'キャビネット', adminReviews: 'レビュー', adminAuditLogs: '監査ログ' },
    ko: { home: '홈', cabinets: '공간', profile: '프로필', myBookings: '내 예약', ownerDashboard: '소유자 대시보드', ownerCabinets: '내 공간', ownerBookings: '예약', ownerServices: '서비스', adminDashboard: '관리자 대시보드', adminUsers: '사용자', adminOwners: '소유자', adminCabinets: '공간', adminReviews: '리뷰', adminAuditLogs: '감사 로그' },
    ar: { home: 'الرئيسية', cabinets: 'المساحات', profile: 'الملف الشخصي', myBookings: 'حجوزاتي', ownerDashboard: 'لوحة المالك', ownerCabinets: 'مساحاتي', ownerBookings: 'الحجوزات', ownerServices: 'الخدمات', adminDashboard: 'لوحة الإدارة', adminUsers: 'المستخدمون', adminOwners: 'المالكون', adminCabinets: 'المساحات', adminReviews: 'التقييمات', adminAuditLogs: 'سجلات التدقيق' },
    tr: { home: 'Ana sayfa', cabinets: 'Odalar', profile: 'Profil', myBookings: 'Rezervasyonlarım', ownerDashboard: 'Sahip paneli', ownerCabinets: 'Odalarım', ownerBookings: 'Rezervasyonlar', ownerServices: 'Hizmetler', adminDashboard: 'Yönetici paneli', adminUsers: 'Kullanıcılar', adminOwners: 'Sahipler', adminCabinets: 'Odalar', adminReviews: 'Yorumlar', adminAuditLogs: 'Denetim kayıtları' },
    hi: { home: 'होम', cabinets: 'कैबिनेट', profile: 'प्रोफ़ाइल', myBookings: 'मेरी बुकिंग', ownerDashboard: 'मालिक डैशबोर्ड', ownerCabinets: 'मेरे कैबिनेट', ownerBookings: 'बुकिंग', ownerServices: 'सेवाएं', adminDashboard: 'एडमिन डैशबोर्ड', adminUsers: 'उपयोगकर्ता', adminOwners: 'मालिक', adminCabinets: 'कैबिनेट', adminReviews: 'समीक्षाएं', adminAuditLogs: 'ऑडिट लॉग' },
} as const

const errors = {
    es: { VALIDATION_ERROR: 'La validación falló. Revisa el formulario.', NOT_FOUND: 'No se encontró el recurso solicitado.', INTERNAL_SERVER_ERROR: 'Algo salió mal. Inténtalo más tarde.', BAD_REQUEST: 'Solicitud no válida.', UNAUTHORIZED: 'Inicia sesión para continuar.', FORBIDDEN: 'No tienes permiso para realizar esta acción.', CONFLICT: 'Se produjo un conflicto.', TOO_MANY_REQUESTS: 'Demasiadas solicitudes. Inténtalo más despacio.', CSRF_ORIGIN_MISMATCH: 'Falló la comprobación de seguridad.', CSRF_TOKEN_MISMATCH: 'La sesión caducó o no es válida.', CABINET_IMAGE_TOO_LARGE: 'La imagen es demasiado grande (máximo 1 MB).', CABINET_IMAGE_UNSUPPORTED_TYPE: 'Tipo de imagen no compatible. Usa JPEG, PNG o WebP.', CABINET_IMAGE_INVALID_CONTENT: 'El archivo de imagen está dañado o no es válido.', EMAIL_VERIFICATION_REQUIRED: 'Verifica tu correo para realizar esta acción.' },
    de: { VALIDATION_ERROR: 'Validierung fehlgeschlagen. Bitte prüfe das Formular.', NOT_FOUND: 'Die angeforderte Ressource wurde nicht gefunden.', INTERNAL_SERVER_ERROR: 'Es ist ein Fehler aufgetreten. Bitte später erneut versuchen.', BAD_REQUEST: 'Ungültige Anfrage.', UNAUTHORIZED: 'Bitte anmelden, um fortzufahren.', FORBIDDEN: 'Keine Berechtigung für diese Aktion.', CONFLICT: 'Ein Konflikt ist aufgetreten.', TOO_MANY_REQUESTS: 'Zu viele Anfragen. Bitte später erneut versuchen.', CSRF_ORIGIN_MISMATCH: 'Sicherheitsprüfung fehlgeschlagen.', CSRF_TOKEN_MISMATCH: 'Sitzung abgelaufen oder ungültig.', CABINET_IMAGE_TOO_LARGE: 'Das Bild ist zu groß (maximal 1 MB).', CABINET_IMAGE_UNSUPPORTED_TYPE: 'Nicht unterstützter Bildtyp. Verwende JPEG, PNG oder WebP.', CABINET_IMAGE_INVALID_CONTENT: 'Die Bilddatei ist beschädigt oder ungültig.', EMAIL_VERIFICATION_REQUIRED: 'Bitte E-Mail bestätigen, um diese Aktion auszuführen.' },
    fr: { VALIDATION_ERROR: 'La validation a échoué. Vérifiez le formulaire.', NOT_FOUND: 'La ressource demandée est introuvable.', INTERNAL_SERVER_ERROR: 'Une erreur est survenue. Réessayez plus tard.', BAD_REQUEST: 'Requête invalide.', UNAUTHORIZED: 'Connectez-vous pour continuer.', FORBIDDEN: 'Vous n’avez pas l’autorisation pour cette action.', CONFLICT: 'Un conflit est survenu.', TOO_MANY_REQUESTS: 'Trop de requêtes. Veuillez patienter.', CSRF_ORIGIN_MISMATCH: 'La vérification de sécurité a échoué.', CSRF_TOKEN_MISMATCH: 'La session a expiré ou est invalide.', CABINET_IMAGE_TOO_LARGE: 'L’image est trop volumineuse (1 Mo maximum).', CABINET_IMAGE_UNSUPPORTED_TYPE: 'Type d’image non pris en charge. Utilisez JPEG, PNG ou WebP.', CABINET_IMAGE_INVALID_CONTENT: 'Le fichier image est corrompu ou invalide.', EMAIL_VERIFICATION_REQUIRED: 'Vérifiez votre e-mail pour effectuer cette action.' },
    pt: { VALIDATION_ERROR: 'A validação falhou. Verifique o formulário.', NOT_FOUND: 'O recurso solicitado não foi encontrado.', INTERNAL_SERVER_ERROR: 'Algo deu errado. Tente novamente mais tarde.', BAD_REQUEST: 'Solicitação inválida.', UNAUTHORIZED: 'Entre para continuar.', FORBIDDEN: 'Você não tem permissão para realizar esta ação.', CONFLICT: 'Ocorreu um conflito.', TOO_MANY_REQUESTS: 'Muitas solicitações. Tente mais tarde.', CSRF_ORIGIN_MISMATCH: 'A verificação de segurança falhou.', CSRF_TOKEN_MISMATCH: 'A sessão expirou ou é inválida.', CABINET_IMAGE_TOO_LARGE: 'A imagem é muito grande (máximo de 1 MB).', CABINET_IMAGE_UNSUPPORTED_TYPE: 'Tipo de imagem não suportado. Use JPEG, PNG ou WebP.', CABINET_IMAGE_INVALID_CONTENT: 'O arquivo de imagem está corrompido ou é inválido.', EMAIL_VERIFICATION_REQUIRED: 'Verifique seu e-mail para realizar esta ação.' },
    zh: { VALIDATION_ERROR: '验证失败，请检查表单。', NOT_FOUND: '未找到请求的资源。', INTERNAL_SERVER_ERROR: '服务器出现问题，请稍后重试。', BAD_REQUEST: '请求无效。', UNAUTHORIZED: '请登录后继续。', FORBIDDEN: '你没有执行此操作的权限。', CONFLICT: '发生冲突。', TOO_MANY_REQUESTS: '请求过于频繁，请稍后再试。', CSRF_ORIGIN_MISMATCH: '安全检查失败。', CSRF_TOKEN_MISMATCH: '会话已过期或无效。', CABINET_IMAGE_TOO_LARGE: '图片过大（最大 1 MB）。', CABINET_IMAGE_UNSUPPORTED_TYPE: '不支持的图片类型，请使用 JPEG、PNG 或 WebP。', CABINET_IMAGE_INVALID_CONTENT: '图片文件损坏或无效。', EMAIL_VERIFICATION_REQUIRED: '请验证邮箱后再执行此操作。' },
    ja: { VALIDATION_ERROR: '入力内容を確認してください。', NOT_FOUND: '指定されたリソースが見つかりません。', INTERNAL_SERVER_ERROR: '問題が発生しました。後でもう一度お試しください。', BAD_REQUEST: 'リクエストが無効です。', UNAUTHORIZED: '続行するにはログインしてください。', FORBIDDEN: 'この操作を行う権限がありません。', CONFLICT: '競合が発生しました。', TOO_MANY_REQUESTS: 'リクエストが多すぎます。少し待ってください。', CSRF_ORIGIN_MISMATCH: 'セキュリティチェックに失敗しました。', CSRF_TOKEN_MISMATCH: 'セッションの有効期限が切れているか無効です。', CABINET_IMAGE_TOO_LARGE: '画像が大きすぎます（最大1MB）。', CABINET_IMAGE_UNSUPPORTED_TYPE: '対応していない画像形式です。JPEG、PNG、WebPを使用してください。', CABINET_IMAGE_INVALID_CONTENT: '画像ファイルが破損しているか無効です。', EMAIL_VERIFICATION_REQUIRED: 'この操作にはメール確認が必要です。' },
    ko: { VALIDATION_ERROR: '유효성 검사에 실패했습니다. 양식을 확인하세요.', NOT_FOUND: '요청한 리소스를 찾을 수 없습니다.', INTERNAL_SERVER_ERROR: '문제가 발생했습니다. 나중에 다시 시도하세요.', BAD_REQUEST: '잘못된 요청입니다.', UNAUTHORIZED: '계속하려면 로그인하세요.', FORBIDDEN: '이 작업을 수행할 권한이 없습니다.', CONFLICT: '충돌이 발생했습니다.', TOO_MANY_REQUESTS: '요청이 너무 많습니다. 잠시 후 다시 시도하세요.', CSRF_ORIGIN_MISMATCH: '보안 확인에 실패했습니다.', CSRF_TOKEN_MISMATCH: '세션이 만료되었거나 유효하지 않습니다.', CABINET_IMAGE_TOO_LARGE: '이미지가 너무 큽니다(최대 1MB).', CABINET_IMAGE_UNSUPPORTED_TYPE: '지원하지 않는 이미지 형식입니다. JPEG, PNG 또는 WebP를 사용하세요.', CABINET_IMAGE_INVALID_CONTENT: '이미지 파일이 손상되었거나 유효하지 않습니다.', EMAIL_VERIFICATION_REQUIRED: '이 작업을 수행하려면 이메일을 인증하세요.' },
    ar: { VALIDATION_ERROR: 'فشل التحقق. يرجى مراجعة النموذج.', NOT_FOUND: 'لم يتم العثور على المورد المطلوب.', INTERNAL_SERVER_ERROR: 'حدث خطأ. يرجى المحاولة لاحقًا.', BAD_REQUEST: 'الطلب غير صالح.', UNAUTHORIZED: 'سجّل الدخول للمتابعة.', FORBIDDEN: 'ليس لديك صلاحية لهذا الإجراء.', CONFLICT: 'حدث تعارض.', TOO_MANY_REQUESTS: 'طلبات كثيرة جدًا. يرجى الانتظار.', CSRF_ORIGIN_MISMATCH: 'فشل التحقق الأمني.', CSRF_TOKEN_MISMATCH: 'انتهت الجلسة أو أصبحت غير صالحة.', CABINET_IMAGE_TOO_LARGE: 'الصورة كبيرة جدًا (الحد الأقصى 1 ميجابايت).', CABINET_IMAGE_UNSUPPORTED_TYPE: 'نوع الصورة غير مدعوم. استخدم JPEG أو PNG أو WebP.', CABINET_IMAGE_INVALID_CONTENT: 'ملف الصورة تالف أو غير صالح.', EMAIL_VERIFICATION_REQUIRED: 'يرجى تأكيد بريدك لتنفيذ هذا الإجراء.' },
    tr: { VALIDATION_ERROR: 'Doğrulama başarısız. Formu kontrol edin.', NOT_FOUND: 'İstenen kaynak bulunamadı.', INTERNAL_SERVER_ERROR: 'Bir sorun oluştu. Daha sonra tekrar deneyin.', BAD_REQUEST: 'Geçersiz istek.', UNAUTHORIZED: 'Devam etmek için giriş yapın.', FORBIDDEN: 'Bu işlem için izniniz yok.', CONFLICT: 'Bir çakışma oluştu.', TOO_MANY_REQUESTS: 'Çok fazla istek var. Daha sonra tekrar deneyin.', CSRF_ORIGIN_MISMATCH: 'Güvenlik kontrolü başarısız oldu.', CSRF_TOKEN_MISMATCH: 'Oturumun süresi doldu veya geçersiz.', CABINET_IMAGE_TOO_LARGE: 'Görüntü çok büyük (en fazla 1 MB).', CABINET_IMAGE_UNSUPPORTED_TYPE: 'Desteklenmeyen görüntü türü. JPEG, PNG veya WebP kullanın.', CABINET_IMAGE_INVALID_CONTENT: 'Görüntü dosyası bozuk veya geçersiz.', EMAIL_VERIFICATION_REQUIRED: 'Bu işlem için e-postanızı doğrulayın.' },
    hi: { VALIDATION_ERROR: 'सत्यापन विफल हुआ। फ़ॉर्म जांचें।', NOT_FOUND: 'अनुरोधित संसाधन नहीं मिला।', INTERNAL_SERVER_ERROR: 'कुछ गलत हुआ। कृपया बाद में प्रयास करें।', BAD_REQUEST: 'अमान्य अनुरोध।', UNAUTHORIZED: 'जारी रखने के लिए साइन इन करें।', FORBIDDEN: 'आपको यह कार्रवाई करने की अनुमति नहीं है।', CONFLICT: 'संघर्ष हुआ।', TOO_MANY_REQUESTS: 'बहुत अधिक अनुरोध। बाद में प्रयास करें।', CSRF_ORIGIN_MISMATCH: 'सुरक्षा जांच विफल हुई।', CSRF_TOKEN_MISMATCH: 'सत्र समाप्त हो गया है या अमान्य है।', CABINET_IMAGE_TOO_LARGE: 'छवि बहुत बड़ी है (अधिकतम 1 MB)।', CABINET_IMAGE_UNSUPPORTED_TYPE: 'असमर्थित छवि प्रकार। JPEG, PNG या WebP इस्तेमाल करें।', CABINET_IMAGE_INVALID_CONTENT: 'छवि फ़ाइल खराब या अमान्य है।', EMAIL_VERIFICATION_REQUIRED: 'यह कार्रवाई करने के लिए ईमेल सत्यापित करें।' },
} as const

const security = {
    es: { accountLocked: { title: 'Cuenta bloqueada temporalmente' }, refreshTokenReuse: { title: 'Alerta de seguridad' } },
    de: { accountLocked: { title: 'Konto vorübergehend gesperrt' }, refreshTokenReuse: { title: 'Sicherheitswarnung' } },
    fr: { accountLocked: { title: 'Compte temporairement bloqué' }, refreshTokenReuse: { title: 'Alerte de sécurité' } },
    pt: { accountLocked: { title: 'Conta bloqueada temporariamente' }, refreshTokenReuse: { title: 'Alerta de segurança' } },
    zh: { accountLocked: { title: '账户暂时锁定' }, refreshTokenReuse: { title: '安全提醒' } },
    ja: { accountLocked: { title: 'アカウントが一時的にロックされました' }, refreshTokenReuse: { title: 'セキュリティ警告' } },
    ko: { accountLocked: { title: '계정이 일시적으로 잠겼습니다' }, refreshTokenReuse: { title: '보안 경고' } },
    ar: { accountLocked: { title: 'تم قفل الحساب مؤقتًا' }, refreshTokenReuse: { title: 'تنبيه أمني' } },
    tr: { accountLocked: { title: 'Hesap geçici olarak kilitlendi' }, refreshTokenReuse: { title: 'Güvenlik uyarısı' } },
    hi: { accountLocked: { title: 'खाता अस्थायी रूप से लॉक है' }, refreshTokenReuse: { title: 'सुरक्षा चेतावनी' } },
} as const

const payment = {
    es: { completed: { title: 'Pago completado' }, failed: { title: 'Pago fallido' } },
    de: { completed: { title: 'Zahlung abgeschlossen' }, failed: { title: 'Zahlung fehlgeschlagen' } },
    fr: { completed: { title: 'Paiement effectué' }, failed: { title: 'Échec du paiement' } },
    pt: { completed: { title: 'Pagamento concluído' }, failed: { title: 'Falha no pagamento' } },
    zh: { completed: { title: '付款完成' }, failed: { title: '付款失败' } },
    ja: { completed: { title: '支払いが完了しました' }, failed: { title: '支払いに失敗しました' } },
    ko: { completed: { title: '결제가 완료되었습니다' }, failed: { title: '결제에 실패했습니다' } },
    ar: { completed: { title: 'اكتملت عملية الدفع' }, failed: { title: 'فشلت عملية الدفع' } },
    tr: { completed: { title: 'Ödeme tamamlandı' }, failed: { title: 'Ödeme başarısız' } },
    hi: { completed: { title: 'भुगतान पूरा हुआ' }, failed: { title: 'भुगतान विफल हुआ' } },
} as const

const bookingEmails = {
    es: { subject: { created: 'Solicitud de reserva enviada - AutoCare Hub', createdOwner: 'Nueva solicitud de reserva - AutoCare Hub', confirmed: 'Reserva confirmada - AutoCare Hub', cancelled: 'Reserva cancelada - AutoCare Hub' }, title: { created: 'Solicitud de reserva enviada', createdOwner: 'Nueva solicitud de reserva', confirmed: 'Reserva confirmada', cancelled: 'Reserva cancelada' }, description: { created: 'Tu solicitud de reserva se ha enviado al propietario y está pendiente de confirmación.', createdOwner: 'Has recibido una nueva solicitud de reserva para tu cabinete.', confirmed: 'El propietario ha confirmado tu reserva.', cancelled: 'Se ha cancelado una reserva.' }, details: { header: 'Detalles de la reserva:', cabinet: 'Cabinete:', service: 'Servicio:', date: 'Fecha:', time: 'Hora:' } },
    de: { subject: { created: 'Buchungsanfrage gesendet - AutoCare Hub', createdOwner: 'Neue Buchungsanfrage - AutoCare Hub', confirmed: 'Buchung bestätigt - AutoCare Hub', cancelled: 'Buchung storniert - AutoCare Hub' }, title: { created: 'Buchungsanfrage gesendet', createdOwner: 'Neue Buchungsanfrage', confirmed: 'Buchung bestätigt', cancelled: 'Buchung storniert' }, description: { created: 'Deine Buchungsanfrage wurde an den Eigentümer gesendet und wartet auf Bestätigung.', createdOwner: 'Du hast eine neue Buchungsanfrage für deinen Raum erhalten.', confirmed: 'Der Eigentümer hat deine Buchung bestätigt.', cancelled: 'Eine Buchung wurde storniert.' }, details: { header: 'Buchungsdetails:', cabinet: 'Raum:', service: 'Leistung:', date: 'Datum:', time: 'Zeit:' } },
    fr: { subject: { created: 'Demande de réservation envoyée - AutoCare Hub', createdOwner: 'Nouvelle demande de réservation - AutoCare Hub', confirmed: 'Réservation confirmée - AutoCare Hub', cancelled: 'Réservation annulée - AutoCare Hub' }, title: { created: 'Demande de réservation envoyée', createdOwner: 'Nouvelle demande de réservation', confirmed: 'Réservation confirmée', cancelled: 'Réservation annulée' }, description: { created: 'Votre demande a été envoyée au propriétaire et attend sa confirmation.', createdOwner: 'Vous avez reçu une nouvelle demande pour votre cabinet.', confirmed: 'Le propriétaire a confirmé votre réservation.', cancelled: 'Une réservation a été annulée.' }, details: { header: 'Détails de la réservation :', cabinet: 'Cabinet :', service: 'Service :', date: 'Date :', time: 'Heure :' } },
    pt: { subject: { created: 'Solicitação de reserva enviada - AutoCare Hub', createdOwner: 'Nova solicitação de reserva - AutoCare Hub', confirmed: 'Reserva confirmada - AutoCare Hub', cancelled: 'Reserva cancelada - AutoCare Hub' }, title: { created: 'Solicitação de reserva enviada', createdOwner: 'Nova solicitação de reserva', confirmed: 'Reserva confirmada', cancelled: 'Reserva cancelada' }, description: { created: 'Sua solicitação foi enviada ao proprietário e aguarda confirmação.', createdOwner: 'Você recebeu uma nova solicitação de reserva para sua sala.', confirmed: 'O proprietário confirmou sua reserva.', cancelled: 'Uma reserva foi cancelada.' }, details: { header: 'Detalhes da reserva:', cabinet: 'Sala:', service: 'Serviço:', date: 'Data:', time: 'Horário:' } },
    zh: { subject: { created: '预订请求已发送 - AutoCare Hub', createdOwner: '新的预订请求 - AutoCare Hub', confirmed: '预订已确认 - AutoCare Hub', cancelled: '预订已取消 - AutoCare Hub' }, title: { created: '预订请求已发送', createdOwner: '新的预订请求', confirmed: '预订已确认', cancelled: '预订已取消' }, description: { created: '您的预订请求已发送给房主，等待确认。', createdOwner: '您收到了一条新的房间预订请求。', confirmed: '房主已确认您的预订。', cancelled: '一条预订已被取消。' }, details: { header: '预订详情：', cabinet: '房间：', service: '服务：', date: '日期：', time: '时间：' } },
    ja: { subject: { created: '予約リクエストを送信しました - AutoCare Hub', createdOwner: '新しい予約リクエスト - AutoCare Hub', confirmed: '予約が確定しました - AutoCare Hub', cancelled: '予約がキャンセルされました - AutoCare Hub' }, title: { created: '予約リクエストを送信しました', createdOwner: '新しい予約リクエスト', confirmed: '予約が確定しました', cancelled: '予約がキャンセルされました' }, description: { created: '予約リクエストをオーナーに送信しました。確認をお待ちください。', createdOwner: 'キャビネットへの新しい予約リクエストが届きました。', confirmed: 'オーナーが予約を確認しました。', cancelled: '予約がキャンセルされました。' }, details: { header: '予約の詳細:', cabinet: 'キャビネット:', service: 'サービス:', date: '日付:', time: '時間:' } },
    ko: { subject: { created: '예약 요청 전송 - AutoCare Hub', createdOwner: '새 예약 요청 - AutoCare Hub', confirmed: '예약 확정 - AutoCare Hub', cancelled: '예약 취소 - AutoCare Hub' }, title: { created: '예약 요청이 전송되었습니다', createdOwner: '새 예약 요청', confirmed: '예약이 확정되었습니다', cancelled: '예약이 취소되었습니다' }, description: { created: '예약 요청이 소유자에게 전송되었으며 확인을 기다리고 있습니다.', createdOwner: '공간에 대한 새 예약 요청을 받았습니다.', confirmed: '소유자가 예약을 확정했습니다.', cancelled: '예약이 취소되었습니다.' }, details: { header: '예약 세부 정보:', cabinet: '공간:', service: '서비스:', date: '날짜:', time: '시간:' } },
    ar: { subject: { created: 'تم إرسال طلب الحجز - AutoCare Hub', createdOwner: 'طلب حجز جديد - AutoCare Hub', confirmed: 'تم تأكيد الحجز - AutoCare Hub', cancelled: 'تم إلغاء الحجز - AutoCare Hub' }, title: { created: 'تم إرسال طلب الحجز', createdOwner: 'طلب حجز جديد', confirmed: 'تم تأكيد الحجز', cancelled: 'تم إلغاء الحجز' }, description: { created: 'تم إرسال طلب الحجز إلى المالك وينتظر التأكيد.', createdOwner: 'لقد تلقيت طلب حجز جديدًا لمساحتك.', confirmed: 'أكد المالك حجزك.', cancelled: 'تم إلغاء حجز.' }, details: { header: 'تفاصيل الحجز:', cabinet: 'المساحة:', service: 'الخدمة:', date: 'التاريخ:', time: 'الوقت:' } },
    tr: { subject: { created: 'Rezervasyon talebi gönderildi - AutoCare Hub', createdOwner: 'Yeni rezervasyon talebi - AutoCare Hub', confirmed: 'Rezervasyon onaylandı - AutoCare Hub', cancelled: 'Rezervasyon iptal edildi - AutoCare Hub' }, title: { created: 'Rezervasyon talebi gönderildi', createdOwner: 'Yeni rezervasyon talebi', confirmed: 'Rezervasyon onaylandı', cancelled: 'Rezervasyon iptal edildi' }, description: { created: 'Rezervasyon talebiniz sahibine gönderildi ve onay bekliyor.', createdOwner: 'Odanız için yeni bir rezervasyon talebi aldınız.', confirmed: 'Sahip rezervasyonunuzu onayladı.', cancelled: 'Bir rezervasyon iptal edildi.' }, details: { header: 'Rezervasyon ayrıntıları:', cabinet: 'Oda:', service: 'Hizmet:', date: 'Tarih:', time: 'Saat:' } },
    hi: { subject: { created: 'बुकिंग अनुरोध भेजा गया - AutoCare Hub', createdOwner: 'नया बुकिंग अनुरोध - AutoCare Hub', confirmed: 'बुकिंग की पुष्टि हुई - AutoCare Hub', cancelled: 'बुकिंग रद्द हुई - AutoCare Hub' }, title: { created: 'बुकिंग अनुरोध भेजा गया', createdOwner: 'नया बुकिंग अनुरोध', confirmed: 'बुकिंग की पुष्टि हुई', cancelled: 'बुकिंग रद्द हुई' }, description: { created: 'आपका बुकिंग अनुरोध मालिक को भेज दिया गया है और पुष्टि की प्रतीक्षा है।', createdOwner: 'आपको अपने कैबिनेट के लिए नया बुकिंग अनुरोध मिला है।', confirmed: 'मालिक ने आपकी बुकिंग की पुष्टि कर दी है।', cancelled: 'एक बुकिंग रद्द कर दी गई है।' }, details: { header: 'बुकिंग विवरण:', cabinet: 'कैबिनेट:', service: 'सेवा:', date: 'तारीख:', time: 'समय:' } },
} as const

const emails = {
    es: { common: { hello: 'Hola {{name}},', viewDetails: 'Consulta los detalles en tu cuenta', footer: 'Si no esperabas este correo, puedes ignorarlo.' }, passwordSetup: { subject: 'Configura tu contraseña - AutoCare Hub', title: 'Configura tu contraseña', button: 'Configurar contraseña', expiry: 'Este enlace caducará el {{expiry}}.' }, passwordReset: { subject: 'Restablece tu contraseña - AutoCare Hub', title: 'Restablece tu contraseña', button: 'Restablecer contraseña', expiry: 'Este enlace caducará el {{expiry}}.' }, emailVerification: { subject: 'Verifica tu correo - AutoCare Hub', title: 'Verifica tu correo', button: 'Verificar correo', expiry: 'Este enlace caducará el {{expiry}}.' } },
    de: { common: { hello: 'Hallo {{name}},', viewDetails: 'Details im Konto anzeigen', footer: 'Wenn du diese E-Mail nicht erwartet hast, kannst du sie ignorieren.' }, passwordSetup: { subject: 'Passwort festlegen - AutoCare Hub', title: 'Passwort festlegen', button: 'Passwort festlegen', expiry: 'Dieser Link läuft am {{expiry}} ab.' }, passwordReset: { subject: 'Passwort zurücksetzen - AutoCare Hub', title: 'Passwort zurücksetzen', button: 'Passwort zurücksetzen', expiry: 'Dieser Link läuft am {{expiry}} ab.' }, emailVerification: { subject: 'E-Mail bestätigen - AutoCare Hub', title: 'E-Mail bestätigen', button: 'E-Mail bestätigen', expiry: 'Dieser Link läuft am {{expiry}} ab.' } },
    fr: { common: { hello: 'Bonjour {{name}},', viewDetails: 'Voir les détails dans votre compte', footer: 'Si vous n’attendiez pas cet e-mail, vous pouvez l’ignorer.' }, passwordSetup: { subject: 'Définir votre mot de passe - AutoCare Hub', title: 'Définir votre mot de passe', button: 'Définir le mot de passe', expiry: 'Ce lien expirera le {{expiry}}.' }, passwordReset: { subject: 'Réinitialiser votre mot de passe - AutoCare Hub', title: 'Réinitialiser votre mot de passe', button: 'Réinitialiser le mot de passe', expiry: 'Ce lien expirera le {{expiry}}.' }, emailVerification: { subject: 'Vérifier votre e-mail - AutoCare Hub', title: 'Vérifier votre e-mail', button: 'Vérifier l’e-mail', expiry: 'Ce lien expirera le {{expiry}}.' } },
    pt: { common: { hello: 'Olá {{name}},', viewDetails: 'Ver detalhes na sua conta', footer: 'Se você não esperava este e-mail, pode ignorá-lo.' }, passwordSetup: { subject: 'Defina sua senha - AutoCare Hub', title: 'Defina sua senha', button: 'Definir senha', expiry: 'Este link expirará em {{expiry}}.' }, passwordReset: { subject: 'Redefina sua senha - AutoCare Hub', title: 'Redefina sua senha', button: 'Redefinir senha', expiry: 'Este link expirará em {{expiry}}.' }, emailVerification: { subject: 'Verifique seu e-mail - AutoCare Hub', title: 'Verifique seu e-mail', button: 'Verificar e-mail', expiry: 'Este link expirará em {{expiry}}.' } },
    zh: { common: { hello: '你好，{{name}}：', viewDetails: '在账户中查看详情', footer: '如果你没有预期收到此邮件，可以忽略它。' }, passwordSetup: { subject: '设置密码 - AutoCare Hub', title: '设置密码', button: '设置密码', expiry: '此链接将于 {{expiry}} 过期。' }, passwordReset: { subject: '重置密码 - AutoCare Hub', title: '重置密码', button: '重置密码', expiry: '此链接将于 {{expiry}} 过期。' }, emailVerification: { subject: '验证邮箱 - AutoCare Hub', title: '验证邮箱', button: '验证邮箱', expiry: '此链接将于 {{expiry}} 过期。' } },
    ja: { common: { hello: '{{name}}さん、', viewDetails: 'アカウントで詳細を確認', footer: 'このメールに心当たりがない場合は、そのまま無視してください。' }, passwordSetup: { subject: 'パスワードを設定 - AutoCare Hub', title: 'パスワードを設定', button: 'パスワードを設定', expiry: 'このリンクは{{expiry}}に期限切れになります。' }, passwordReset: { subject: 'パスワードをリセット - AutoCare Hub', title: 'パスワードをリセット', button: 'パスワードをリセット', expiry: 'このリンクは{{expiry}}に期限切れになります。' }, emailVerification: { subject: 'メールアドレスを確認 - AutoCare Hub', title: 'メールアドレスを確認', button: 'メールを確認', expiry: 'このリンクは{{expiry}}に期限切れになります。' } },
    ko: { common: { hello: '{{name}}님,', viewDetails: '계정에서 자세히 보기', footer: '이 이메일을 요청하지 않았다면 무시해도 됩니다.' }, passwordSetup: { subject: '비밀번호 설정 - AutoCare Hub', title: '비밀번호 설정', button: '비밀번호 설정', expiry: '이 링크는 {{expiry}}에 만료됩니다.' }, passwordReset: { subject: '비밀번호 재설정 - AutoCare Hub', title: '비밀번호 재설정', button: '비밀번호 재설정', expiry: '이 링크는 {{expiry}}에 만료됩니다.' }, emailVerification: { subject: '이메일 인증 - AutoCare Hub', title: '이메일 인증', button: '이메일 인증', expiry: '이 링크는 {{expiry}}에 만료됩니다.' } },
    ar: { common: { hello: 'مرحبًا {{name}}،', viewDetails: 'عرض التفاصيل في حسابك', footer: 'إذا لم تكن تتوقع هذا البريد، يمكنك تجاهله بأمان.' }, passwordSetup: { subject: 'إعداد كلمة المرور - AutoCare Hub', title: 'إعداد كلمة المرور', button: 'إعداد كلمة المرور', expiry: 'ستنتهي صلاحية هذا الرابط في {{expiry}}.' }, passwordReset: { subject: 'إعادة تعيين كلمة المرور - AutoCare Hub', title: 'إعادة تعيين كلمة المرور', button: 'إعادة تعيين كلمة المرور', expiry: 'ستنتهي صلاحية هذا الرابط في {{expiry}}.' }, emailVerification: { subject: 'تأكيد بريدك الإلكتروني - AutoCare Hub', title: 'تأكيد بريدك الإلكتروني', button: 'تأكيد البريد الإلكتروني', expiry: 'ستنتهي صلاحية هذا الرابط في {{expiry}}.' } },
    tr: { common: { hello: 'Merhaba {{name}},', viewDetails: 'Ayrıntıları hesabınızda görüntüleyin', footer: 'Bu e-postayı beklemiyorsanız güvenle yok sayabilirsiniz.' }, passwordSetup: { subject: 'Şifrenizi belirleyin - AutoCare Hub', title: 'Şifrenizi belirleyin', button: 'Şifre belirle', expiry: 'Bu bağlantının süresi {{expiry}} tarihinde dolacak.' }, passwordReset: { subject: 'Şifrenizi sıfırlayın - AutoCare Hub', title: 'Şifrenizi sıfırlayın', button: 'Şifreyi sıfırla', expiry: 'Bu bağlantının süresi {{expiry}} tarihinde dolacak.' }, emailVerification: { subject: 'E-postanızı doğrulayın - AutoCare Hub', title: 'E-postanızı doğrulayın', button: 'E-postayı doğrula', expiry: 'Bu bağlantının süresi {{expiry}} tarihinde dolacak.' } },
    hi: { common: { hello: 'नमस्ते {{name}},', viewDetails: 'अपने खाते में विवरण देखें', footer: 'यदि आपको इस ईमेल की अपेक्षा नहीं थी, तो इसे अनदेखा कर सकते हैं।' }, passwordSetup: { subject: 'पासवर्ड सेट करें - AutoCare Hub', title: 'पासवर्ड सेट करें', button: 'पासवर्ड सेट करें', expiry: 'यह लिंक {{expiry}} को समाप्त हो जाएगा।' }, passwordReset: { subject: 'पासवर्ड रीसेट करें - AutoCare Hub', title: 'पासवर्ड रीसेट करें', button: 'पासवर्ड रीसेट करें', expiry: 'यह लिंक {{expiry}} को समाप्त हो जाएगा।' }, emailVerification: { subject: 'ईमेल सत्यापित करें - AutoCare Hub', title: 'ईमेल सत्यापित करें', button: 'ईमेल सत्यापित करें', expiry: 'यह लिंक {{expiry}} को समाप्त हो जाएगा।' } },
} as const

export const esTranslations = createPopularLocale({ common: common.es, navigation: navigation.es, errors: errors.es, notifications: { security: security.es, payment: payment.es }, emails: { ...emails.es, booking: bookingEmails.es } })
export const deTranslations = createPopularLocale({ common: common.de, navigation: navigation.de, errors: errors.de, notifications: { security: security.de, payment: payment.de }, emails: { ...emails.de, booking: bookingEmails.de } })
export const frTranslations = createPopularLocale({ common: common.fr, navigation: navigation.fr, errors: errors.fr, notifications: { security: security.fr, payment: payment.fr }, emails: { ...emails.fr, booking: bookingEmails.fr } })
export const ptTranslations = createPopularLocale({ common: common.pt, navigation: navigation.pt, errors: errors.pt, notifications: { security: security.pt, payment: payment.pt }, emails: { ...emails.pt, booking: bookingEmails.pt } })
export const zhTranslations = createPopularLocale({ common: common.zh, navigation: navigation.zh, errors: errors.zh, notifications: { security: security.zh, payment: payment.zh }, emails: { ...emails.zh, booking: bookingEmails.zh } })
export const jaTranslations = createPopularLocale({ common: common.ja, navigation: navigation.ja, errors: errors.ja, notifications: { security: security.ja, payment: payment.ja }, emails: { ...emails.ja, booking: bookingEmails.ja } })
export const koTranslations = createPopularLocale({ common: common.ko, navigation: navigation.ko, errors: errors.ko, notifications: { security: security.ko, payment: payment.ko }, emails: { ...emails.ko, booking: bookingEmails.ko } })
export const arTranslations = createPopularLocale({ common: common.ar, navigation: navigation.ar, errors: errors.ar, notifications: { security: security.ar, payment: payment.ar }, emails: { ...emails.ar, booking: bookingEmails.ar } })
export const trTranslations = createPopularLocale({ common: common.tr, navigation: navigation.tr, errors: errors.tr, notifications: { security: security.tr, payment: payment.tr }, emails: { ...emails.tr, booking: bookingEmails.tr } })
export const hiTranslations = createPopularLocale({ common: common.hi, navigation: navigation.hi, errors: errors.hi, notifications: { security: security.hi, payment: payment.hi }, emails: { ...emails.hi, booking: bookingEmails.hi } })
