export {
    automotiveServices,
    getServiceLabel,
    getProviderProfile,
    providerProfiles,
    providerPreviews,
    type AutomotivePriceType,
    type AutomotiveService,
    type ProviderOffering,
    type ProviderProfile,
    type ProviderPreview,
    type ProviderReview,
} from './model/autocareMockData'
export { automotiveVehicleBrands, getVehicleBrandLabel, type AutomotiveVehicleBrandId } from './model/vehicleBrands'
export { getVehicleModels } from './model/vehicleModels'
export { getVehicleBrand, vehicleCatalog, vehicleFuelTypes, type VehicleBrandOption, type VehicleEngineOption, type VehicleFuelType, type VehicleModelOption } from './model/vehicleCatalog'
export {
    automotiveAmenities,
    defaultAutomotiveAmenityIds,
    getAutomotiveAmenityLabel,
    type AutomotiveAmenity,
    type AutomotiveAmenityId,
} from './model/automotiveAmenities'
export { AutomotiveAmenityIcon } from './ui/AutomotiveAmenityIcon'
export { ProviderLogo } from './ui/ProviderLogo'
export { ServiceRequestChat } from './ui/ServiceRequestChat'
export {
    useGetAutoCareDiscoveryQuery,
    useGetAutoCareMarketsQuery,
    useUpdateSuperAdminAutoCareMarketMutation,
    useGetAutoCareLocationZonesQuery,
    useGetOwnerAutoCareProvidersQuery,
    useGetOwnerAutoCareProviderAnalyticsQuery,
    useGetOwnerAutoCareProviderMembersQuery,
    useInviteAutoCareProviderMemberMutation,
    useRevokeAutoCareProviderInvitationMutation,
    useRevokeAutoCareProviderMembershipMutation,
    useAcceptAutoCareProviderInvitationMutation,
    useGetOwnerAutoCareProviderChangeRequestsQuery,
    useCreateOwnerAutoCareProviderChangeRequestMutation,
    useCancelOwnerAutoCareProviderChangeRequestMutation,
    useGetAdminAutoCareProviderChangeRequestsQuery,
    useDecideAdminAutoCareProviderChangeRequestMutation,
    useCreateAutoCareCatalogGapRequestMutation,
    useGetAdminCatalogGapRequestsQuery,
    useDecideAdminCatalogGapRequestMutation,
    useGetAdminAutoCareChatReportsQuery,
    useDecideAdminAutoCareChatReportMutation,
    useGetMyAutoCareBonusAccountsQuery,
    useRedeemAutoCareBonusMutation,
    useGrantAutoCareBonusMutation,
    useGetOwnerAutoCareBonusProgramQuery,
    useUpsertOwnerAutoCareBonusProgramMutation,
    useUpdateOwnerAutoCareOfferMutation,
    useGetOwnerAutoCareProviderReviewsQuery,
    useGetOwnerAutoCareReviewsQuery,
    useIssueOwnerAutoCareReviewPromoMutation,
    useGetMyAutoCareReviewsQuery,
    useGetMyAutoCareAppealsQuery,
    useCreateAutoCareAppealMutation,
    useCreateAutoCareReviewMutation,
    useRedeemAutoCareReviewPromoMutation,
    useUpdateAutoCareReviewMutation,
    useGetAdminAutoCareProvidersQuery,
    useUpdateAdminAutoCareProviderStatusMutation,
    useGetAdminAutoCareAppealsQuery,
    useDecideAdminAutoCareAppealMutation,
    useGetSuperAdminPlatformOverviewQuery,
    useUploadOwnerAutoCareProviderLogoMutation,
    useUploadOwnerAutoCareProviderMediaMutation,
    useGetAutoCareProviderProfileQuery,
    useGetAutoCareProviderReviewsQuery,
    useGetAutoCareFavoritesQuery,
    useAddAutoCareFavoriteMutation,
    useRemoveAutoCareFavoriteMutation,
    useSyncAutoCareFavoritesMutation,
    useGetAutoCareAvailabilityQuery,
    useGetAutoCareFairPriceQuery,
    useGetAutoCareProviderTrustQuery,
    useGetAutoCareServiceDefinitionsQuery,
    useGetVehicleCatalogQuery,
    useGetFeaturedAutoCareReviewsQuery,
    useCreateOwnerAutoCareProviderMutation,
    useCreateAutoCareServiceRequestMutation,
    useGetMyAutoCareServiceRequestsQuery,
    useGetAutoCareChatsQuery,
    useCreateAutoCareChatMutation,
    useGetAutoCareChatQuery,
    useCreateAutoCareChatMessageMutation,
    useCreateAutoCareChatReportMutation,
    useCreateAutoCareChatBlockMutation,
    useRevokeAutoCareChatBlockMutation,
    useMarkAutoCareChatReadMutation,
    useCreateAutoCareChatAttachmentMutation,
    useGetAutoCareServiceRequestQuery,
    useGetAutoCareRepairTimelineQuery,
    useCreateAutoCareBroadcastRequestMutation,
    useGetMyAutoCareBroadcastRequestsQuery,
    useGetAutoCareBroadcastRequestQuery,
    useGetOwnerAutoCareBroadcastRequestsQuery,
    useCreateAutoCareBroadcastOfferMutation,
    useCreateAutoCareGuaranteeClaimMutation,
    useGetMyAutoCareGuaranteeClaimsQuery,
    useCreateAutoCareExpertQuestionMutation,
    useGetMyAutoCareExpertQuestionsQuery,
    useGetMyAutoCareFleetsQuery,
    useCreateAutoCareFleetMutation,
    useCreateAutoCareFleetVehicleMutation,
    useConfirmAutoCareServiceRequestMutation,
    useCancelAutoCareServiceRequestMutation,
    useDecideAutoCareServiceRescheduleMutation,
    useAcceptAutoCareServiceQuoteMutation,
    useDeclineAutoCareServiceQuoteMutation,
    useGetOwnerAutoCareServiceRequestsQuery,
    useConfirmOwnerAutoCareServiceRequestMutation,
    useGetAutoCareServiceConversationQuery,
    useCreateAutoCareServiceMessageMutation,
    useCreateAutoCareServiceOfferMutation,
    useDecideAutoCareServiceOfferMutation,
    useMarkAutoCareServiceConversationReadMutation,
    useCreateAutoCareServiceAttachmentMutation,
    useCreateAutoCareServiceQuoteMutation,
    useRequestAutoCareServiceRescheduleMutation,
    useMarkAutoCareServiceRequestNoShowMutation,
    useCompleteAutoCareServiceRequestMutation,
} from './api/autocareApi'
export type {
    AutoCareApiDiscoveryItem,
    AutoCareApiDiscoveryResponse,
    AutoCareApiMarket,
    AutoCareApiLocationZone,
    AutoCareApiOffer,
    UpdateAutoCareOfferInput,
    AutoCareApiProvider,
    AutoCareApiProviderReviews,
    OwnerAutoCareReviews,
    OwnerAutoCareReviewsProvider,
    AutoCareApiProviderProfile,
    AutoCareProviderAnalytics,
    AutoCareProviderMember,
    AutoCareProviderInvitation,
    AutoCareProviderMembersResponse,
    AutoCareProviderChangeRequest,
    CreateAutoCareProviderChangeRequestInput,
    DecideAutoCareProviderChangeRequestInput,
    AutoCareCatalogGapRequest,
    CreateAutoCareCatalogGapRequestInput,
    DecideAutoCareCatalogGapRequestInput,
    CreateAutoCareProviderInvitationInput,
    AcceptAutoCareProviderInvitationInput,
    AutoCareFavorite,
    AdminAutoCareProvider,
    SuperAdminPlatformOverview,
    AutoCareApiReview,
    AutoCareAppeal,
    CreateAutoCareAppealInput,
    AutoCareBonusAccount,
    AutoCareBonusLedgerEntry,
    AutoCareBonusProgram,
    OwnerAutoCareBonusProgramInput,
    AutoCareReviewPromo,
    IssueAutoCareReviewPromoInput,
    RedeemAutoCareReviewPromoInput,
    UpdateAutoCareReviewInput,
    CreateAutoCareReviewInput,
    AutoCareAvailability,
    AutoCareApiServiceDefinition,
    AutoCareVehicleBrand,
    AutoCareVehicleEngine,
    AutoCareVehicleModel,
    AutoCareDiscoveryQuery,
    CreateOwnerAutoCareProviderInput,
    AutoCareServiceRequest,
    AutoCareReschedule,
    AutoCareServiceQuote,
    AutoCareQuoteLineItem,
    AutoCarePriceBenchmark,
    AutoCareRepairEvent,
    AutoCareBroadcastOffer,
    AutoCareBroadcastRequest,
    CreateAutoCareBroadcastRequestInput,
    CreateAutoCareBroadcastOfferInput,
    AutoCareTrustEvidence,
    AutoCareTrustResponse,
    AutoCareGuaranteeClaim,
    CreateAutoCareGuaranteeClaimInput,
    AutoCareExpertQuestion,
    CreateAutoCareExpertQuestionInput,
    AutoCareFleet,
    AutoCareFleetVehicle,
    CreateAutoCareFleetInput,
    CreateAutoCareFleetVehicleInput,
    CreateAutoCareServiceRequestInput,
    AutoCareServiceConversation,
    AutoCareChatThread,
    AutoCareChatConversation,
    AutoCareChatReport,
    AutoCareChatBlock,
    AutoCareChatThreadType,
    CreateAutoCareChatInput,
    CreateAutoCareChatMessageInput,
    CreateAutoCareChatReportInput,
    CreateAutoCareChatBlockInput,
    RevokeAutoCareChatBlockInput,
    DecideAutoCareChatReportInput,
    CreateAutoCareChatAttachmentInput,
    AutoCareServiceMessage,
    AutoCareServiceMessageOffer,
    AutoCareServiceAttachment,
    CreateAutoCareServiceMessageInput,
    CreateAutoCareServiceOfferInput,
    DecideAutoCareServiceOfferInput,
    CreateAutoCareServiceAttachmentInput,
    CreateAutoCareServiceQuoteInput,
    CompleteAutoCareServiceRequestInput,
} from './api/autocareApi'
export { mapAutoCareDiscoveryItem, mapAutoCareProviderProfile } from './lib/autocareApiMappers'
export { supportsVehicleBrand } from './lib/brandSpecialization'
export { connectAutoCareChat, connectServiceChat, emitMockAutoCareChatEvent, type ServiceChatEvent, type ServiceChatMessage } from './lib/service-chat'
