export {
    automotiveServices,
    getServiceLabel,
    getProviderProfile,
    providerProfiles,
    providerPreviews,
    type AutomotivePriceType,
    type AutomotiveService,
    type ProviderOffering,
    type ProviderProfile,
    type ProviderPreview,
    type ProviderReview,
} from './model/autocareMockData'
export { automotiveVehicleBrands, getVehicleBrandLabel, type AutomotiveVehicleBrandId } from './model/vehicleBrands'
export { getVehicleModels } from './model/vehicleModels'
export { getVehicleBrand, vehicleCatalog, vehicleFuelTypes, type VehicleBrandOption, type VehicleEngineOption, type VehicleFuelType, type VehicleModelOption } from './model/vehicleCatalog'
export {
    automotiveAmenities,
    defaultAutomotiveAmenityIds,
    getAutomotiveAmenityLabel,
    type AutomotiveAmenity,
    type AutomotiveAmenityId,
} from './model/automotiveAmenities'
export { AutomotiveAmenityIcon } from './ui/AutomotiveAmenityIcon'
export { ProviderLogo } from './ui/ProviderLogo'
export {
    useGetAutoCareDiscoveryQuery,
    useGetAutoCareMarketsQuery,
    useGetOwnerAutoCareProvidersQuery,
    useGetOwnerAutoCareProviderReviewsQuery,
    useGetAdminAutoCareProvidersQuery,
    useUpdateAdminAutoCareProviderStatusMutation,
    useGetSuperAdminPlatformOverviewQuery,
    useUploadOwnerAutoCareProviderLogoMutation,
    useGetAutoCareProviderProfileQuery,
    useGetAutoCareAvailabilityQuery,
    useGetAutoCareServiceDefinitionsQuery,
    useGetVehicleCatalogQuery,
    useGetFeaturedAutoCareReviewsQuery,
    useCreateOwnerAutoCareProviderMutation,
    useCreateAutoCareServiceRequestMutation,
    useGetMyAutoCareServiceRequestsQuery,
    useGetAutoCareServiceRequestQuery,
    useConfirmAutoCareServiceRequestMutation,
    useAcceptAutoCareServiceQuoteMutation,
    useDeclineAutoCareServiceQuoteMutation,
    useGetOwnerAutoCareServiceRequestsQuery,
    useConfirmOwnerAutoCareServiceRequestMutation,
    useGetAutoCareServiceConversationQuery,
    useCreateAutoCareServiceMessageMutation,
    useCreateAutoCareServiceAttachmentMutation,
    useCreateAutoCareServiceQuoteMutation,
} from './api/autocareApi'
export type {
    AutoCareApiDiscoveryItem,
    AutoCareApiDiscoveryResponse,
    AutoCareApiMarket,
    AutoCareApiOffer,
    AutoCareApiProvider,
    AutoCareApiProviderReviews,
    AutoCareApiProviderProfile,
    AdminAutoCareProvider,
    SuperAdminPlatformOverview,
    AutoCareApiReview,
    AutoCareAvailability,
    AutoCareApiServiceDefinition,
    AutoCareVehicleBrand,
    AutoCareVehicleEngine,
    AutoCareVehicleModel,
    AutoCareDiscoveryQuery,
    CreateOwnerAutoCareProviderInput,
    AutoCareServiceRequest,
    CreateAutoCareServiceRequestInput,
    AutoCareServiceConversation,
    AutoCareServiceMessage,
    AutoCareServiceAttachment,
    CreateAutoCareServiceMessageInput,
    CreateAutoCareServiceAttachmentInput,
    CreateAutoCareServiceQuoteInput,
} from './api/autocareApi'
export { mapAutoCareDiscoveryItem, mapAutoCareProviderProfile } from './lib/autocareApiMappers'
export { supportsVehicleBrand } from './lib/brandSpecialization'
